### ISSUE TITLE
Vector subscript out of range (segfault) when doing a second run right after the first

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#100]
Reproduction steps:

1. Start WindNinja GUI on windows
2. Select Mass consistent solver
3. Select mackay.tif
4. Select domain average initialization, 2 mph and 2 deg
5. Select Google Earth output
6. Click Solve
7. Close the progress dialog
8. Click Solve again

In debug mode, the OS catches the vector subscript out of range.  I am checking linux with valgrind now.

**Comment by nwagenbrenner** [comment]
I can replicate this in the current Windows build, but not in the last released version (2.5.4) or in my latest Windows build (at commit e67e6aa).

**Comment by ksshannon** [comment]
Not PDF branch, right?

On Thu, Mar 17, 2016 at 1:56 PM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> I can replicate this in the current Windows build, but not in the last
> released version (2.5.4) or in my latest Windows build (at commit e67e6aa
> <https://github.com/firelab/windninja/commit/e67e6aa496b6a8da5ebe27381c49eb15af618829>
> ).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/100#issuecomment-198057599>
>



-- 
Kyle

**Comment by nwagenbrenner** [comment]
Right, also, not on the PDF branch (at least the build you sent to Jason).

**Comment by nwagenbrenner** [comment]
This issue appears to be gone in the latest build, I can't replicate it anymore. I'll leave it open until we do more testing with the final installer though.

**Comment by nwagenbrenner** [comment]
This isn't happening anymore in master or finish-pdf.
