### ISSUE TITLE
Dialog box hangs after successful NOMADS downloads

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#101]
The progress dialog box gets to 100% and then just hangs and you have to click "cancel" to move forward. The forecast is downloaded properly. This appears to happen for all NOMADS models.

**Comment by nwagenbrenner** [comment]
This happens in the master branch, but not in finish-pdf. On Linux.

**Comment by ksshannon** [comment]
Fixed in 5ad7bbabd43bfeeecc3be45cd234475b6d293f5f.  Was CMake related.  Cleared up ifdefs to be more consistent.
