### ISSUE TITLE
Script building of third party dependencies.

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#11]
Boost 1.46.1
curl 7.40.0
gdal 1.11.1
geos 3.4.2
netcdf 4.3.2
proj 4.8.0
Qt 4.8.5
zlib 1.2.8

**Comment by ksshannon** [comment]
If this can be done in cmake, use cmake.  If we have to bump the required version, do so.  Otherwise, python or shell/bat.

**Comment by nwagenbrenner** [comment]
Isn't this done? Has anyone used the script Levi wrote (scripts/build_deps.sh)?

**Comment by ksshannon** [comment]
I haven't, but I think Jason has.  Works for me.

**Comment by jforthofer** [comment]
I can't remember if it did...  but it looks OK.  I'll close.
