### ISSUE TITLE
selection method doesn't match action button in DEM fetcher

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#110]
On the first launch of the DEM fetcher, the selection method in the drop down menu is set to "Drag Box On Map", but the button is set to "Select Point on Map". So the only way to use the drag box on map method is to pick a different option in the drop down menu, then switch back to Drag Box on Map. After you switch and switch back, the button says "Drag Box On Map" and behaves properly. This only happens the first time the fetcher is used.

**Comment by ksshannon** [comment]
Is it only the first time the application is opened ever?

**Comment by ksshannon** [comment]
Natalie, let me know if that didn't work.
