### ISSUE TITLE
Run progress dialog needs to update text during simulation

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#112]
After an OpenFOAM simulation is started and the progress dialog window opens, the text in the window says "Initializing runs..." for the whole simulation.  Seems like it should say other stuff, like "Meshing", "Solving", etc.

**Comment by ksshannon** [comment]
Retarget to 3.1.0 if needed.

**Comment by nwagenbrenner** [comment]
I changed it to say "Running..." It will take some work to update the text properly. This is good enough for now.

**Comment by ksshannon** [comment]
I think we just need to hook up the proper com in the gui, this should be automagic.

**Comment by nwagenbrenner** [comment]
I think you closed the wrong issue?

**Comment by nwagenbrenner** [comment]
I don't see an easy way to do this since the text is set like:

https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L1977

but we want it to update during

https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L1984-1986

**Comment by ksshannon** [comment]
Maybe update the slot updateProgress() to take a string too?  Then connect
with ninjaCom.

https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L2058-L2067

On Tue, Jun 21, 2016 at 11:56 AM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> I don't see an easy way to do this since the text is set like:
>
>
> https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L1977
>
> but we want it to update during
>
>
> https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L1984-1986
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/firelab/windninja/issues/112#issuecomment-227520030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwVDUbSKsyhy9qZuoYD2J8a39zjcCljks5qOCXJgaJpZM4IEswI>
> .
>



-- 
Kyle

**Comment by nwagenbrenner** [comment]
Fixed in 093f953.
