### ISSUE TITLE
Pdf writer should work the same for all base maps

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#113]
Natalie's testing today showed that the output pdf writer isn't doing margins, etc properly when the base map is topofire.

**Comment by nwagenbrenner** [comment]
For example, see:

[pref_0_4_117m.pdf](https://github.com/firelab/windninja/files/216304/pref_0_4_117m.pdf)

**Comment by ksshannon** [comment]
We'll have to set the output of warping topofire/calfire output to be consistent.  Obviously we do this with the hillshade, so we just need a way to pass the target x and y resolution to the topofire request.  It looks like we may have to adjust the geotransform and the x and y size, overriding the defaults, but we can do that through the options parameter.  

This is me just thinking out loud, have to check on feasability.

**Comment by ksshannon** [comment]
mak
