### ISSUE TITLE
add white space between icons/legend in pdf writer 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#114]
Right now there is no white space between the images (see attached). I think there should be some white space between the icons/legend. I would say just space them equally. So if all three are there (i.e., it's a topofire basemap), put the two logos in the left and right corners and the legend in the middle. If it's just a hillshade, put the WN logo in one corner and the legend in the other. Maybe always put the WN logo in the same place (lower right or lower left). It would also be nice to have some white space between the images and the edge of the page, if that's possible.

[pref_220_4_117m.pdf](https://github.com/firelab/windninja/files/216295/pref_220_4_117m.pdf)

**Comment by ksshannon** [comment]
This is purely a function of the bottom margin height and output size.  There is no whitespace only in the portrait 8.5x11 case.  I think if I scale and center the logos in the y direction (maybe 90% of what they are now), then we should have a better display.
