### ISSUE TITLE
enable pdf writer for ninjafoam

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#115]
The legend and icons need to be added and margins need to be set correctly for ninjafoam runs. Basically, whatever happens in ninja::writeOutputFiles needs to happen in ninjafoam::WriteOutputFiles.

**Comment by ksshannon** [comment]
Okay, should be relatively straight forward to compare the diffs when we merge.

**Comment by nwagenbrenner** [comment]
I think this was closed with 9f62bbe.
