### ISSUE TITLE
NINJAFOAM temp directory not being deleted on Windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#116]

**Comment by nwagenbrenner** [comment]
Weird, everything is deleted except NINJAFOAM_*/foam.tif with NinjaUnlinkTree(pszTempPath). All the case files, etc. are deleted. This only happens on Windows. On linux the entire directory is deleted as it should be.

**Comment by ksshannon** [comment]
Should be fixed with 2598f6e11ddd2cc08c57996375414413e0c5c9ff
