### ISSUE TITLE
pdf output error in ninjafoam runs with diurnal on

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#123]
I'm getting a strange error at the end of the simulation about not finding the pdf basemap. Only seems to happen when diurnal is used with ninjafoam??

**Comment by nwagenbrenner** [comment]
This problem seems to have emerged after 1ecdb36.

**Comment by nwagenbrenner** [comment]
Only seems to happen intermittently and only in the master branch. The last Windows installer we put out for testing doesn't seem to have this problem. Maybe someone else can confirm whether or not this happens for them??

**Comment by ksshannon** [comment]
Appears to be fixed with 235d6ec4cc0ab72ecb3e6fcbbc171cb1bb6db069, reopen if needed.
