### ISSUE TITLE
Cloud cover output file resolution is wrong for CFD runs

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#126]
The cloud cover output file (one of the fire behavior output files) is the wrong resolution for a CFD run.  For my CFD run, with "use mesh resolution" selected for the output resolution, the cloud cover file's resolution was finer than the mesh resolution (but the .ang and .vel file resolutions were correct).

The cloud cover file resolution for native solver runs when only uniform cloud cover information is known (like in a CFD run) outputs files that are only 2x2 cells that over the whole simulation domain.  This reduces disk size and writing time.  The CFD solver should also do this.

**Comment by nwagenbrenner** [comment]
Fixed in b6422e5.
