### ISSUE TITLE
pdf problems on Windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#127]
Looks like there are some issues related to icons, etc. being written to the temp directory. Also, we fail trying to download the topofire map. Maybe this is all related to the temp directory problems. Here's a screenshot of console output with CPL_DEBUG=NINJA.

![pdfproblem](https://cloud.githubusercontent.com/assets/3696653/14961775/ae2dca22-1058-11e6-99f3-56b9c2cbb0dc.png)

**Comment by ksshannon** [comment]
Can you confirm if no output was written at all?

**Comment by nwagenbrenner** [comment]
A pdf is written, but it's always the hillshade and the WindNinja logo is missing (but the legend is there). Also, demName.tif.aux.xml is not cleaned up.

**Comment by ksshannon** [comment]
Thanks

On Mon, May 2, 2016 at 1:44 PM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> A pdf is written, but it's always the hillshade and the WindNinja logo is
> missing (but the legend is there). Also, demName.tif.aux.xml is not cleaned
> up.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/127#issuecomment-216341068>
>



-- 
Kyle

**Comment by ksshannon** [comment]
I can't seem to replicate on win32 here.  It looks like yours attempted to download the relief map, failed, and then made the hillshade, which is correct, as long as it can't really download the relief.  Is there any info about that failure?  Was it only on a ninjafoam run?  I'll poke a bit.  my output attached (I'm filing a ticket about the bad margins).
[mackay_0_3_393m.pdf](https://github.com/firelab/windninja/files/246267/mackay_0_3_393m.pdf)

**Comment by nwagenbrenner** [comment]
What I reported was a native solver run. I tried several times and always had these same problems. I could never get anything but a hillshade. I can try again tomorrow. Any other details that would be helpful? I think @jforthofer tried too and had the same issues.

**Comment by ksshannon** [comment]
Any output from CPL_DEBUG referring to the WMS fail.  The error logic for the logo is loose, maybe I'll tighten it up and try to provide more info.

**Comment by ksshannon** [comment]
Natalie, a760dde94682ac61661546e8d204c1b96c830d97 should have fixed the logo issue.  Maybe the CPL_DEBUG for the download and CPL_CURL_VERBOSE=ON as well...

**Comment by nwagenbrenner** [comment]
Are we missing relief.xml in the Windows installer? I see this on linux:

Open(), filename=[/home/natalie/src/windninja/windninja/data/relief.xml]

And on windows: Error 4: `' does not exist in the file system,...

**Comment by ksshannon** [comment]
That would do it.  Can you check that in?  I don't have WindNinja at work.

On Tue, May 3, 2016 at 8:26 AM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> Are we missing relief.xml in the Windows installer? I see this on linux:
>
> Open(), filename=[/home/natalie/src/windninja/windninja/data/relief.xml]
>
> And on windows: Error 4: `' does not exist in the file system,...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/127#issuecomment-216545664>
>



-- 
Kyle

**Comment by nwagenbrenner** [comment]
Yeah, does it just go in share/windninja?

**Comment by ksshannon** [comment]
Yes.

On Tue, May 3, 2016 at 9:01 AM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> Yeah, does it just go in share/windninja?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/127#issuecomment-216556578>
>



-- 
Kyle

**Comment by nwagenbrenner** [comment]
Looks to be fixed with 31c1d53 and 2a84dbe.
