### ISSUE TITLE
pdf temp files not cleaned up

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#133]
dem.tif.aux.xml is still left over.

**Comment by ksshannon** [comment]
Natalie,  I thought this was the hillshade stuff.  Is this not deleted by the recursive delete function?  GDALDeleteDataset(GDALDriverH, const char*) will usually (tif for sure) delete all associated files.  See:

http://gdal.org/classGDALDriver.html#ad40d369db18eb0af6fbe7e46dd112aed

Reassign to me if this can wait until tonight.

**Comment by ksshannon** [comment]
Okay, I'm confused.  What file is left over?  The aux file for the input DEM, or the hillshade?

**Comment by nwagenbrenner** [comment]
The file has the name "dem.tif.aux.xml" where "dem" is the name of the DEM file on disk. Not sure where this temp file is created without looking further.

**Comment by ksshannon** [comment]
That is a 'sidecar' file generated by gdal when statistics are calculated.  It may or may not already be on disk when we ask for stats.  I think that the DEM actually owns that, and we shouldn't delete it.  It doesn't do any harm, and can be used in future runs.

**Comment by nwagenbrenner** [comment]
Yeah, looks like it's written to a temp directory on Windows, so I think it's fine to leave it. On linux it just gets left in the wd.

**Comment by ksshannon** [comment]
Hmm.  That might not be right.  It should get written to the dem path.  I'm going to reopen and take a look, but push to 3.1.0 if that is okay.

**Comment by nwagenbrenner** [comment]
Oops, I lied. That file is left in the dem directory. On linux that was the same as the wd and on my last Windows run I used topofire for the basemap, so didn't have the issue. This only happens when we create the hillshade. Sorry for the confusion. Not sure we should just leave it there in the output directory...? It will just look like garbage to the user...
