### ISSUE TITLE
Add credit for 3rd party libs to the Help -> About page

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#135]
We should list the 3rd party software we use where normal users can see it, maybe in the Help - > About page.  Might need to add tabs or something to About for this and adding a "Contributors" section as mentioned in #118.

**Comment by ksshannon** [comment]
#118 has some related work

**Comment by ksshannon** [comment]
@tfinney9 do you want me to handle this?

**Comment by tfinney9** [comment]
@ksshannon Sure, thanks.

**Comment by ksshannon** [comment]
@jforthofer can you clarify what you want?  Authors or organizations?

**Comment by jforthofer** [comment]
In the end, we need to give credit for both authors of code directly used in WindNinja (like the UAB group's improved solver) and for the third party code and data we use (NOMADS, MesoWest/Synoptic Labs, etc.).

**Comment by ksshannon** [comment]
And you want this in the GUI?  Or should we just link to a wiki page?

On Tue, Jul 17, 2018, at 09:33, Jason Forthofer wrote:
> In the end, we need to give credit for both authors of code directly 
> used in WindNinja (like the UAB group's improved solver) and for the 
> third party code and data we use (NOMADS, MesoWest/Synoptic Labs, etc.).
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/firelab/windninja/issues/135#issuecomment-405625766


-- 
Kyle

**Comment by jforthofer** [comment]
Seems like the GUI somewhere would be a good place, but if not a link to a web page would be fine.

**Comment by ksshannon** [comment]
I propose we add a link, then update the CREDITS file to serve this purpose, pointing to the most recent version.

**Comment by jforthofer** [comment]
Not sure I completely understand, but go for it. Just so we somehow give credit...

**Comment by nwagenbrenner** [comment]
Good enough for now, we can re-open/open a new ticket if we decide to change how this is done.
