### ISSUE TITLE
GDAL plugins not being installed in NSIS

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#137]
In the gisinternals.com builds, netCDF and some other drivers are compiled as plugins.  The plugins need to be installed alongside WindNinja in bin/gdalplugins, and GDAL_DRIVER_PATH may or may not have to be set.

**Comment by ksshannon** [comment]
@jforthofer this is the kind of issue that would have been caught if testing was done how we discussed while I was in MSO.  Fairly trivial fix, and now a we have to wait a week.  Totally my bug, but we should have caught it earlier this week.

**Comment by jforthofer** [comment]
I agree, we just don't have someone with time to do all the testing...
