### ISSUE TITLE
atm file gets written when it shouldn't

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#140]
If you turn on atm file writing, but turn off "Fire Behavior" file writing, the atm file is still written even though it shouldn't be because the files the atm file references are not there.  This seems to occur for wx model mass conserving runs and not domain average mass conserving runs.  I haven't tried any other runs (like CFD or point).

**Comment by nwagenbrenner** [comment]
How did you select atm file output without selecting Fire Behavior file writing? Do you mean you selected Fire Behavior, then Create *.atm file(s), then you unselected Fire Behavior?

**Comment by ksshannon** [comment]
There isn't a great way to fix this, either uncheck (magically) the atm box when the fb output is unchecked, or issue a warning to the user.  Also `writeAtm` should be changed to `writeAtm && writeFb` here:

https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L1925

That should prevent this from slipping through, although how we notify the user needs to be handled.  Do we stop the run and warn, or just go?

**Comment by nwagenbrenner** [comment]
This is exactly what I was just looking at. I think we should just uncheck the atm box when the fb output is unchecked. The atm output is useless without the ascii files anyway, right? I don't think we need to warn the user, just don't write it if fb isn't checked when the simulation is started. I think if this happens, it's by accident anyway, not someone intentionally trying to generate the atm file without the fb files. @jforthofer can have the final word when he's back tomorrow.

**Comment by ksshannon** [comment]
Copy, the line of code should be changed anyway, in case there is some GUI thing that we miss, agreed?

**Comment by nwagenbrenner** [comment]
Yep, I agree with that.

**Comment by jforthofer** [comment]
Natalie, yes, to get it to happen you turn on writing of fire behavior outputs, check the write atm box, then turn off fire behavior outputs.
I think the desired behavior from a user perspective should be that if fire behavior outputs are unchecked the atm file doesn't get written (even if it's checked in the grayed out part).  I don't think we should automatically uncheck the atm file box when the user unchecks the fire behavior outputs.  It's nice if the GUI "remembers" whether the atm box was checked or not, so if you turn fire behavior outputs back on the atm box is in the state you left it (either checked or unchecked).

**Comment by ksshannon** [comment]
Jason,

We don't save the state of that checkbox, AFAIK:

https://github.com/firelab/windninja/blob/master/src/gui/mainWindow.cpp#L137-L166

On Tue, May 17, 2016 at 9:57 AM, Jason Forthofer <notifications@github.com>
wrote:

> Natalie, yes, to get it to happen you turn on writing of fire behavior
> outputs, check the write atm box, then turn off fire behavior outputs.
> I think the desired behavior from a user perspective should be that if
> fire behavior outputs are unchecked the atm file doesn't get written (even
> if it's checked in the grayed out part). I don't think we should
> automatically uncheck the atm file box when the user unchecks the fire
> behavior outputs. It's nice if the GUI "remembers" whether the atm box was
> checked or not, so if you turn fire behavior outputs back on the atm box is
> in the state you left it (either checked or unchecked).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/140#issuecomment-219764658>
>



-- 
Kyle

**Comment by jforthofer** [comment]
That's fine if the setting isn't saved after you close WindNinja.  But it would be nice if at least it saves during a WindNinja GUI instance.

**Comment by nwagenbrenner** [comment]
I think a4b0b45 gets around it as best as possible. I'll leave this open until Jason confirms with the new installer.

**Comment by nwagenbrenner** [comment]
Jason, just to confirm, this does not appear to be an issue in the CLI:

https://github.com/firelab/windninja/blob/master/src/ninja/cli.cpp#L1489-L1493
