### ISSUE TITLE
UCAR GFS runs failing

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#149]
Appears to be an issue with time variable names.  Not sure why the GUI isn't catching the exception.

**Comment by ksshannon** [comment]
Need to 
`git cherry-pick 329dae106c0c46c1214a55c0081c0b47a6cd502c` into the 3.0 branch before closing.  Waiting for a quick WRF test from @nwagenbrenner.

**Comment by nwagenbrenner** [comment]
The WRF test ran fine. Using a local wrfout file I had on hand: wrfout_d02_2010-09-04_120000.nc
