### ISSUE TITLE
Intermittent problem with UCAR NAM

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#150]
The error says the downloaded file is not an .nc file. The downloaded file contains this message:

While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

This was happening for a while, but looks like whatever the problem was, it was fixed. Other UCAR models were not affected. If we figure out what's going on maybe we can at least report a better error message. This seems to be a problem on the UCAR side?

**Comment by ksshannon** [comment]
This has been happening for a while, off and on.  I don't know what exactly there issue is, but it can be seen in the travis logs, as it causes most failures (other than the GFS issue that was fixed).  If they return something != 200, we can read the response body and relay it to the user, but that is it.  The exception model makes a good report a little tough.
