### ISSUE TITLE
OpenFOAM meshing fails on very small domains

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#152]
The original blockMesh needs to be slightly smaller than the DEM for moveDynamicMesh to run properly. We set an x/y buffer to handle this when setting the bounds for the blockMesh, but apparently it's not sufficient for very small domains. I saw this problem on a 360 m x 420 m DEM.

**Comment by jforthofer** [comment]
This is why we need to try to make sure everything is set relative to the size of the DEM if possible so that everything works, even for really small DEMs.  Can this be done here?

**Comment by nwagenbrenner** [comment]
Yeah, we were already doing that...

**Comment by ksshannon** [comment]
Natalie, there are 'strange' DEMs in data/ for testing some of this stuff.  skinny ones, tiny ones, etc.  Just FYI.

**Comment by nwagenbrenner** [comment]
Thanks.
