### ISSUE TITLE
Error making on Ubuntu - undefined reference to GDALRasterBand::RasterIO

### ISSUE THREAD

**Issue by piyushnz** [firelab/windninja#157]
I have followed all the instructions for building on Linux (I'm on Ubuntu 14.04) and got most of the way through with no errors until the end of the make && sudo make install step. The last few lines of output are as follows:
`
[ 91%] Building CXX object src/gui/CMakeFiles/WindNinja.dir/GoogleMapsInterface.cpp.o  
[ 91%] Building CXX object src/gui/CMakeFiles/WindNinja.dir/setconfigdialog.cpp.o  
Linking CXX executable WindNinja  
/home/jain/windninja/build/src/ninja/libninja.so: undefined reference to 'GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*)'  
collect2: error: ld returned 1 exit status  
make[2]: *** [src/gui/WindNinja] Error 1  
make[1]: *** [src/gui/CMakeFiles/WindNinja.dir/all] Error 2   
make: *** [all] Error 2  
`
Any ideas how on a fix?

**Comment by ksshannon** [comment]
Can you let me know which version of windninja you are using, and tell me which step is causing the error, make, or make install?

**Comment by piyushnz** [comment]
It occurs in the make step. I am using version 3.0.0

**Comment by ksshannon** [comment]
What version of GDAL is installed?  I can't replicate with 14.04 building against GDAL trunk.  Maybe try running `sudo ldconfig` and then `make clean && make`

**Comment by nwagenbrenner** [comment]
If the current build instructions were followed, build_deps.sh should have installed GDAL 2.0.0 in /usr/local.

https://github.com/firelab/windninja/blob/master/scripts/build_deps.sh

Is that the case?

**Comment by piyushnz** [comment]
running `sudo ldconfig` and then `make clean && make` did not help - same error.

Yes, I ran the build_deps.sh file first and gdal does appear to be installed at /usr/local/bin/

Perhaps the problem is that my I have multiple versions of gdal already installed (one from anaconda and another install at /usr/bin/.)

I therefore tried again resetting the path to
PATH=/usr/local/bin:/bin:/usr/bin

however, after running `sudo ldconfig` and then `make clean && make` I still get the same error.

**Comment by ksshannon** [comment]
Which one did you set the cmake variable to?  Do the header files match up with the library you point to?

**Comment by piyushnz** [comment]
Okay progress: I deleted everything and started again, but set my environment path variable as indicated before running build_dep.sh. I didn't touch the gdal paths in the cmake configuration since they were pointing to /usr/local already. 

The `make` and `sudo make install` now run through to completion without errors. 

However, when I run WindNinja I get the following error:
```
$ WindNinja  
WindNinja: error while loading shared libraries: libninja.so: cannot open shared object file: No such file or directory
```

**Comment by ksshannon** [comment]
Run sudo ldconfig, and if that doesn't work edit LD_LOAD_LIBRARY and add
your path to it.

On Wed, Jun 15, 2016 at 11:21 AM, piyushnz <notifications@github.com> wrote:

> Okay progress: I deleted everything and started again, but set my
> environment path variable as indicated before running build_dep.sh. I
> didn't touch the gdal paths in the cmake configuration since they were
> pointing to /usr/local already.
>
> The make and sudo make install now run through to completion without
> errors.
>
> However, when I run WindNinja I get the following error:
>
> $ WindNinja
> WindNinja: error while loading shared libraries: libninja.so: cannot open shared object file: No such file or directory
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/firelab/windninja/issues/157#issuecomment-226257647>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwVDfmCrseLRSxtMzt-60GFWPczqme-ks5qMDSvgaJpZM4I1tKW>
> .
>



-- 
Kyle

**Comment by piyushnz** [comment]
`sudo ldconfig` did it. Launches the app now.

Thanks!!!

**Comment by jforthofer** [comment]
Kyle, Natalie, should any of this info be added to the Wiki to prevent this problem in the future?

**Comment by ksshannon** [comment]
It's already on there.  It says you may need to run `sudo ldconfig`

**Comment by jforthofer** [comment]
OK, what about "setting the environment path variable"?  Was this just WINDNINJA_DATA, or something else?
