### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#159]
FAQ needs to be updated, mostly windninja vs windwizard.

https://github.com/firelab/windninja/wiki/Frequently-Asked-Questions

**Comment by nwagenbrenner** [comment]
I edited the windninja vs. windwizard sections to be consistent with the info in Tutorial 1. @jforthofer should review.

**Comment by jforthofer** [comment]
Looks great to me, thanks Natalie.  Also thanks to Kyle for pointing this out...

**Comment by nwagenbrenner** [comment]
I updated some of the other content. I think it's good for now.
