### ISSUE TITLE
Multiple Cloud Layers

### ISSUE THREAD

**Issue by tfinney9** [firelab/windninja#162]
Here is a link to the raw data from MesoWest, it opens as text in your browser

api.mesowest.net/v2/stations/timeseries?stid=KMSO&network=1,2,81&vars=cloud_layer_1_code,cloud_layer_2_code,cloud_layer_3_code&output=geojson&recent=1440&token=33e3c8ee12dc499c86de1f2076a9e9d4

**Comment by tfinney9** [comment]
Here is the output from stationfetch 

cloud_layer_1
706.000, 306.000, 653.000, 356.000, 554.000, 502.000, 706.000, 606.000, 603.000, 502.000, 606.000, 503.000, 483.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 
count of doubles: 25

cloud_layer_2
1003.000, 653.000, 1004.000, 553.000, 0.000, 603.000, 903.000, 803.000, 804.000, 703.000, 853.000, 653.000, 654.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 
count of doubles: 25

cloud_layer_3
0.000, 1004.000, 0.000, 0.000, 0.000, 754.000, 0.000, 903.000, 0.000, 803.000, 0.000, 804.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 
count of doubles: 25


I think I was making a mistake in building the URL, it works now. 
https://github.com/firelab/windninja/commit/4b2aa7e8dc48cada6dce6f72b904d873bd770faf

**Comment by ksshannon** [comment]
So this is a no-op?

**Comment by nwagenbrenner** [comment]
Yeah, looks like it. I'll take a closer look.
