### ISSUE TITLE
Prevent duplicate domain average runs in the GUI

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#163]
I accidentally entered a duplicate run in the GUI (e.g., two runs with speed = 2 and direction = 0) and got a segfault during kmz writing (using multiple processors). We should check for duplicates before we start the runs.

ERROR 1: Cannot create big_butte_small_0_2_55m.kml while another file is being written in the .zip

**Comment by ksshannon** [comment]
We should at least fix the segfault, they are bad.
