### ISSUE TITLE
Publish Big Butte (and maybe Birch Creek) data on zenodo

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#164]
Free, get a DOI, yada yada.

**Comment by nwagenbrenner** [comment]
The BSB, SRC, and Birch Creek datasets are here right now: 

https://collab.firelab.org/software/projects/wind-obs/repository

Abby is working on adding benchmarks from BSB and Birch Creek to the WindBench project (http://windbench.net/), so might be good timing for this.

**Comment by ksshannon** [comment]
Published on weather.firelab.org
