### ISSUE TITLE
Add a "clear" button to clear entered domain average inputs

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#165]
After a user has done multiple domain average simulations, and then they want to do more, it would be useful to have a "clear" or "reset" type button at the top that would change all the values back to default values.  The main reason is that if I did like 10 runs, then afterward want to do just 1 more, it's pretty hard to get it set up to just do 1 since we "automagically" determine how many runs the user actually wants from their inputs.  This might speak to the bigger picture of redoing this so it's more like an excel spreadsheet type experience where you could just highlight a row or column and delete or edit, also copy/paste ability.

**Comment by ksshannon** [comment]
Trivial change, AFAIK.  Easy enough for Jason.

**Comment by ksshannon** [comment]
@jforthofer can you check this and see if you'd like the button to look different?

**Comment by jforthofer** [comment]
What do you guys think if the button just had the text "Clear" on it rather than an icon?

**Comment by nwagenbrenner** [comment]
Added text to the button in 116fb54.

**Comment by jforthofer** [comment]
Yeah, looks good to me.  Thanks guys.
