### ISSUE TITLE
WindNinja is accumulating memory

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#166]
When you do multiple domain average runs, then do some more, and more, WindNinja's RAM usage just keeps going up.  Are we forgetting to delete some memory or something?

This is confirmed to happen with both solvers for domain average diurnal runs.  Haven't checked anything else...

**Comment by ksshannon** [comment]
Probably.

**Comment by ksshannon** [comment]
The fix above should help quite a bit.  There is some memory used by libcurl that is probably reused, as we do clean up our request.  There are several thousand bytes taken by boost date time, that don't get freed, ever.  It is difficult to track too.  We should create a global, read-only database in NinjaInit(), and remove all the load_from_file() calls.

**Comment by ksshannon** [comment]
See de5acbcd1f8b32fc1be5db916c2bc8199b597f41 for the global time zone db.  It's potentially a fairly large change, running valgrind with 64 threads on a test.  valgrind_audit for more changes if they come.

**Comment by ksshannon** [comment]
@jforthofer  run your tests again on the valgrind-audit branch, let me know if you are still seeing large amounts of leaking.  Then I can merge back into master.  Run a few tests on some stuff too.

**Comment by ksshannon** [comment]
@jforthofer if you don't post some metric about what you were seeing, I can't know if I have fixed it.

**Comment by nwagenbrenner** [comment]
I think Jason is headed out on a fire, but I  can test this next week. Or
possibly tomorrow.

**Comment by jforthofer** [comment]
Yeah, sorry Kyle but I'm (supposedly) heading to a fire in the Bitteroot tomorrow.  It's simple to replicate though, just follow my instructions above and watch the task manager, you'll see RAM just keeps going up and up when you keep rerunning WindNinja without closing.  After many runs, maybe 10-20 total at coarse resolution, I think WindNinja was at like 1.5 Gb or so just sitting there after all runs are complete.  When you first start WindNinja, it's nowhere near 1.5 Gb just sitting there.
Sorry I can't help right now.  I'm an FBAN trainee on the fire, so should be in camp more than normal and might have time to work a little.

**Comment by ksshannon** [comment]
You just sent me a text from some sort of party.

On Thu, Jun 30, 2016 at 5:50 PM, Jason Forthofer <notifications@github.com>
wrote:

> Yeah, sorry Kyle but I'm (supposedly) heading to a fire in the Bitteroot
> tomorrow. It's simple to replicate though, just follow my instructions
> above and watch the task manager, you'll see RAM just keeps going up and up
> when you keep rerunning WindNinja without closing. After many runs, maybe
> 10-20 total at coarse resolution, I think WindNinja was at like 1.5 Gb or
> so just sitting there after all runs are complete. When you first start
> WindNinja, it's nowhere near 1.5 Gb just sitting there.
> Sorry I can't help right now. I'm an FBAN trainee on the fire, so should
> be in camp more than normal and might have time to work a little.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/firelab/windninja/issues/166#issuecomment-229820112>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwVDaJghOUHYT59UH4dRtzRmfR9FLmPks5qRFZegaJpZM4JBpQu>
> .
>



-- 
Kyle

**Comment by jforthofer** [comment]
Jack Cohen's retirement party.

**Comment by nwagenbrenner** [comment]
Looks like this is fixed in the valgrind_audit branch. I just ran ~20 runs and RAM was basically the same after the runs finished as when I started.
