### ISSUE TITLE
Point Initialization with stability=on doesn't converge

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#17]
Point initialization with stability on and diurnal on doesn't seem to converge for the mackay test case.  It appears the simulation starts to bounce between negative and positive diffs (difference between measured and simulated values at points).

**Comment by jforthofer** [comment]
This is happening on Windows 64-bit, in the "master" branch.  Haven't tested on Linux, but guessing the problem will occur there also.

**Comment by nwagenbrenner** [comment]
I can't replicate this problem on linux. I did several mackay simulations with data/mackay_wx_station.csv and non_neutral_stability = true and diurnal_winds = true and didn't get any errors. I used cli_pointInitiatlization.cfg and just added the diurnal and stability arguments. What cfg or settings did you use?

**Comment by jforthofer** [comment]
The settings that do it are (from the GUI):

mackay.tif
trees
fine mesh resolution
time zone = America/Boise
diurnal=on
stability=on
point initialization using mackay_wx_stations.csv
time = 01/20/2015  15:40
google earth output=on
I ran the simulations with 8 threads on my Windows machine (64-bit version of WindNinja 2.5.0, which is the current "master" in github).

I tried running it today with the current date and time, and the simulation converged...  The date/time listed above does not converge.  So it seems sensitive to the time for some reason...?  No idea why this would happen...  strange.

**Comment by ksshannon** [comment]
Same on linux here.  A few other notes:

* If diurnal is off, it works
* If a coarse mesh is used, it works

**Comment by jforthofer** [comment]
This appears to be a fairly unlikely situation where the iterative solution (the outer iterations, one ninja simulation per iteration) converges to a point that oscillates between the positive and negative values forever.  We are basically using a Newton method to converge to the "matched" solution (final field matches the measured at the points).  After reading this:
http://web.stanford.edu/class/cme304/docs/newton-type-methods.pdf
I see that there might be some simple ways to improve our method.  Page 6, section 2.2 talks about 2 modifications to our Newton method I will try that will hopefully accelerate the convergence in some situations and also prevent divergence in many cases (and hopefully the convergence to this oscillatory solution).

**Comment by ksshannon** [comment]
config that exhibits issue:

num_threads              = 1
elevation_file           = ../data/mackay.tif
initialization_method    = pointInitialization
time_zone                = America/Denver
match_points             = true
wx_station_filename      = ../data/mackay_wx_stations.csv
output_wind_height       = 20.0
units_output_wind_height = ft
vegetation               = trees
mesh_choice              = fine
write_goog_output        = true
diurnal_winds            = true
year                     = 2015
month                    = 1
day                      = 20
hour                     = 15
minute                   = 40
non_neutral_stability    = true

**Comment by jforthofer** [comment]
Looks to be fixed.

**Comment by ksshannon** [comment]
Jason fixed with a dampened newton method.  Merged in 263941faf842722fba46d11d78d7b8bdbbc75134
