### ISSUE TITLE
Write native mesh to format OpenFOAM can use.

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#172]
Possible docs for VTK formats:

http://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf

**Comment by nwagenbrenner** [comment]
New plan is to directly write the OpenFOAM mesh format instead of an intermediate unstructured vtk format.

http://cfd.direct/openfoam/user-guide/mesh-description/

**Comment by nwagenbrenner** [comment]
Basically done. Specific issues can be opened later if needed.
