### ISSUE TITLE
Reduce target number of cells for CFD solver

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#173]
Based on Loren's results from the big butte small terrain I think we could reduce the target number of cells in the ninjafoam mesh. For this terrain there are essentially no visible differences in output between medium and fine. We'll need to test with other terrains too, but maybe we could try:

coarse = 100k --> 50k
medium = 500k --> 100k
fine = 1M --> 500k

**Comment by jforthofer** [comment]
Seems reasonable to me...
