### ISSUE TITLE
Remove ability to initialize a ninjafoam run with an STL

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#178]
We originally had this option so a run could be done straight from an STL (no need for a DEM). But I don't think it's that useful and it added a substantial chunk of code. In fact, since the meshing has been modified, I don't think this even works correctly right now. Also, we have no way to produce our usual output products without a DEM (or some spatial info), so you could view the flow solution in paraview, or pull out info using OpenFOAM tools, but that's about it. If no one else cares, I think I'm going to get rid of it.

**Comment by jforthofer** [comment]
Sounds good.
