### ISSUE TITLE
Ninjafoam fails if there are spaces in the DEM name

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#180]

**Comment by ksshannon** [comment]
How does one replicate?  Likely have to quote the name in the CPLSpawn call, ie CPLSPrintf("\"%s\"", dem);

**Comment by nwagenbrenner** [comment]
If there are any spaces in the DEM name, OpenFOAM fails at several points when it's using that string (i.e., to run surfaceTransformPoints). We give the STL the same basename as the DEM. Maybe just need to omit the spaces in STL name when we write it.
