### ISSUE TITLE
Add option to get different Landfire .lcp versions

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#189]
There are several versions of Landfire .lcp datasets due to Landfire updates.  We need to check which version we are using and make note of that in the GUI so users know.  We should also investigate the possibility of having all datasets available to users.  This came about from issues seen on the Pioneer Fire.

**Comment by ksshannon** [comment]
We were getting the latest at the time of implementation.  I *think* it was the 2012 refresh.  What was the use case?  Did they want the 2008 or older?  I am against providing seldom used options for a very small amount of users.  Perhaps an 'Advanced Options' dialog that sets specific things?  Also taking the GUI tag off, as it will affect the cli too.  We just need to display the version (in my opinion in the 'Advanced Options' configuration dialog).

**Comment by jforthofer** [comment]
The use case was that we wanted to make a map of fuels as a geospatial pdf to put on a phone to  take in the field with us.  It appears that what WindNinja downloads is different than what's on WFDSS.
At the least, we should determine what we're downloading and note that somewhere in the GUI...

**Comment by ksshannon** [comment]
So this has very little to do with windninja. Maybe we just document which
versions we use, and try to keep it up to date.  We'll have to be alerted
when a refresh comes out, maybe Don Long can point us to a source for that?

When we implemented, Hawaii wasn't refreshed yet, it's probably due.

**Comment by jforthofer** [comment]
Yeah, I agree with all that.

**Comment by jforthofer** [comment]
Any word on this from Don?

**Comment by ksshannon** [comment]
Nope. I emailed him of list too. Go up and ask him tomorrow.

**Comment by nwagenbrenner** [comment]
I just talked to Don. He had forwarded the question on to someone else. He's going to check with them again and have someone get back to us.

**Comment by nwagenbrenner** [comment]
Upgraded to the latest lcp data in 80e8ff1: 2016 for conus, 2014 for AK and HI. Codes:

FHY60HZ conus
F0740HZ AK
FCM42HZ HI
