### ISSUE TITLE
Testing plans for WindNinja

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#2]
A testing protocol should be developed before releases.  Basically a list of human-run tests with feedback.  Run all weather models, all data download, etc.  As tests get merged into the autotesting suite, we can discard them.  We'll all have to work on the testing, but Jason gives the last OK.

**Comment by ksshannon** [comment]
A manual list of tests should be written up (here maybe) and checked off by the devs before releasing.  This shouldn't be that hard, and would catch bugs like the one in 2.5.0.  @jforthofer can start on this sooner than later.

**Comment by ksshannon** [comment]
- [ ] Run autotest suite
- [ ] Surface Data
    - [ ] Download LCP from CONUS
    - [ ] Download LCP from Alaska
    - [ ] Download LCP from Hawaii
    - [ ] Download US SRTM
    - [ ] Download US SRTM outside of CONUS, expected fail

**Comment by ksshannon** [comment]
Test list template moved to: https://github.com/firelab/windninja/wiki/Release-Testing

**Comment by ksshannon** [comment]
@jforthofer: how is this coming along???? :smile:

**Comment by jforthofer** [comment]
Kyle's a funny man now...
