### ISSUE TITLE
Ninjafoam fails if the DEM name starts with a number

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#204]
Reported by @jforthofer. We can check for this too and do some renaming I guess. OpenFOAM puts a number of restrictions on file names. Should we check for all of them?

OpenFOAM follows a strict rule to use file names as if they were C/C++ coding names, where the following characteristics must be followed:

 A name can start with an alphabet character or an underscore.
 A name cannot have spaces in it.
 A name cannot start with a digit (0 to 9), but it can have digits in any other place of its name.
 A name cannot have quote symbols, namely: " '
 A name can be a composite of several names, by using dots and parenthesis, namely: . ( )
 A name cannot have unconventional symbols, including there characters: \ / : ;

**Comment by jforthofer** [comment]
Seems like the right thing to do would be to check for all these, even though many would be very unlikely.
