### ISSUE TITLE
NOMADS GFS run fails

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#21]
The simulation blows up after pushing the solve button.  Info:
Windows 64-bit release version
mackay.tif
trees
coarse
America/Boise
diurnal off
stability off
wx model initialization
NOMADS-GFS-GLOBAL-0.25-DEG
6 hrs download
google earth checked
threads = 8

When it blows up, "Generating mesh..." is the last thing written in the console.

**Comment by jforthofer** [comment]
Also fails with 1 thread.

**Comment by jforthofer** [comment]
And fine resolution, 8 threads.

**Comment by ksshannon** [comment]
Fixed in fc630f025c4980daed01061cb6afb36c61d4db0d, use GDALOpenShared for the next fcst file
