### ISSUE TITLE
Exception thrown when using existing case momentum solver

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#210]
Not sure if this is supposed to work or not... but at least we should handle it better than throwing and exception.

I did a normal momentum solver run from scratch (DIURNAL OFF), including building the mesh, etc.  After that, I did another run with the momentum solver and chose the "Use Existing Case" method and picked the run I had just done.  But now, I TURNED ON DIURNAL also.  The run seems to go just fine until the end when it tries to add the diurnal wind in.  After the console output says "Run 0: Adding diurnal winds..." I get an exception that says "Exception caught: Mesh resolution out of range in Mesh::set_meshResolution().".

Is this capability to turn diurnal off and on when using an existing case suppose to work?  Or is it something you're not suppose to be able to do?

**Comment by nwagenbrenner** [comment]
Yes, it should work. I'll look...
