### ISSUE TITLE
Downloaded NOMADS RAP files do not have cloud cover

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#211]
The downloaded files only have TMP, UGRD, and VGRD. No other models (from either source) appear to have this issue.

**Comment by ksshannon** [comment]
I am hoping/suspecting this is growing pains, but I downloaded one file with jp2 grids.  Wait a day, then I'll email NOAA.

**Comment by ksshannon** [comment]
I've sent a email to the NOMADS help desk to clarify.  Reopening in case it was an accident.

**Comment by ksshannon** [comment]
a556411e8aa29416d4e936008ea4d215cf362875 needs to be merged into 3.1 as well (if we are good).

**Comment by ksshannon** [comment]
It is mentioned in the TIN.  I just missed it:

> U and V components of vertical wind shear (Discipline 0, Category 2, Numbers 15 and 16):  The current labeling of the first specified height level above ground as 6000 and the second level as 0 is changed so that 0 is the first level and 6000 is the second.

RAP still sends both, but I think this is harmless.
