### ISSUE TITLE
Change discretization scheme for advection 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#213]
Should we change from cellMDLimited back to QUICK (again)? The cellMDLimited scheme generates regions of low velocity zones that extend far downwind of terrain obstacles. These low velocity zones appear as "streaks" in the flow. It doesn't seem realistic. I have comparison plots demonstrating differences in the flow between the two schemes for mackay and big southern butte. I'll send them out shortly.

**Comment by jforthofer** [comment]
To me they both look like they have problems.  The cellMDLimited scheme has the really bad streaky look, and the QUICK doesn't seem to show enough change in direction and the wakes are too small or non-existent.  Should we look at others?  What do you guys think?

**Comment by nwagenbrenner** [comment]
Too small based on what? The modeled eddy footprint using QUICK compared well with observations at the butte. We presented on that at AGU last year. We can look into other schemes, but we don't have time to do sufficient testing of a new scheme before this release. I guess we'll keep cellMDLimited for now until we can do more testing.

**Comment by jforthofer** [comment]
Just based on my intuition, which could certainly be wrong.  The mackay simulation you sent just doesn't have a lot of wake areas...
Yeah, worst case I think we stick with cellMDLimited for now like you mentioned.

**Comment by nwagenbrenner** [comment]
Yeah, I see what you're saying regarding lack of recirculation in the SW portion of mackay. We should just do some testing of different schemes and comparison with observations (probably with big southern butte and birch creek data).

**Comment by ksshannon** [comment]
Is there literature we can reference for some validity?  Given some parameters (terrain roughness or something), is there precedence?  Seems like some paper would at least mention it.  All of our reasons basically revolve around 'It looks funny'.

**Comment by ksshannon** [comment]
Or maybe the AGU paper is that, for now.

**Comment by nwagenbrenner** [comment]
Yeah, that's a good point too, there's some guidance in the literature, but not a lot. For a number of reasons. There's not a lot of data (in real terrain) for validation, so there aren't a ton of papers. Plus, there are many other settings that affect the final solution: the turbulence model, the mesh itself, the discretization used for the other terms, etc. I'll revisit the papers I have, but I think we'll need to do our own evaluations regardless. Maybe we can work this into a paper.

**Comment by jforthofer** [comment]
I doubt there's a definitive paper.  There are just a ton of discretization schemes people have dreamed up over the years, each with advantages and disadvantages and dependent on specifics like the type of cell (hex, polyhedral, etc.), quality measures of cell, specifics about the flow, even the direction of the flow compared to the cell faces, and many others.
There is some general guidance, which is along the lines of what we talked with Chris about, and we're following that...  but there are huge differences in the flow fields dependent on this choice, which we don't have a good feel for (model is sensitive to a fairly arbitrary parameter).

**Comment by nwagenbrenner** [comment]
We're using linear upwind discretization for the advection term

`div(phi,U)                      bounded Gauss linearUpwind grad(U);`

based on testing against Askervein Hill and Bolund Hill data presented at AGU 2018. Reference available [here](https://www.researchgate.net/publication/330856638_Development_and_Evaluation_of_a_RANS-based_CFD_Solver_in_WindNinja). See ead8ebc.

**Comment by nwagenbrenner** [comment]
Fixed with the merge of the cfd-upgrade branch.
