### ISSUE TITLE
Add more info to gh-pages 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#219]
Stuff to include:

How Does WindNinja Work?
- [ ] mesh construction (for each solver)
- [ ] initialization options/methods (for each solver), including 3D wx model initialization

WindNinja Mobile
- [x] stats from script on AWS (map of recent simulation locations, number of simulations per day, etc.)
- [ ] link to video tutorial (when it's ready)
- [x] screen capture(s)?

Developers and Advanced Users
- [x] Dust simulations

Features in Development
- [x] WindNinja API

**Comment by latwood** [comment]
I can work on the "How Does WindNinja Work?" section. I figure that Tanner will be doing the "Windninja Mobile" section. We'll have to decide who does the other two parts depending on who gets done first.
Loren


-------- Original message --------

**Comment by nwagenbrenner** [comment]
Also add a place to subscribe to the WindNinja mailing list. Maybe at the bottom of the main page. I can get you the code for this.

**Comment by nwagenbrenner** [comment]
Basically done.
