### ISSUE TITLE
Enable station-fetch in the GUI

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#226]

**Comment by ksshannon** [comment]
Started looking at the CLI and the API for it.  I have a few minor changes there.  I'll start tomorrow or Friday.  Not sure how long it will take.  Is @tfinney9  available for consultation/testing?

**Comment by nwagenbrenner** [comment]
I'm available if Tanner isn't.

**Comment by nwagenbrenner** [comment]
What's the status of this? What can I do to help move things forward?

**Comment by nwagenbrenner** [comment]
Duplicate of #194.
