### ISSUE TITLE
Input file contains No Data Values

### ISSUE THREAD

**Issue by kiracool** [firelab/windninja#232]
I found WindNinja through google and saw its tutorial and details, I liked the extent that it can do with Wind and all. I downloaded the setup file and installed the WindNinja application. I am having issues with importing the input file, when ever I import my DEM file (.tif) it says the input file has no data value but I can see that DEM file in my QGIS platform.
Can anybody help me out with this.

**Comment by nwagenbrenner** [comment]
WindNinja requires that all cells in the DEM contain values. This is explained in Section 3.1.1 of Tutorial 1:

http://firelab.github.io/windninja/pdf/WindNinja_tutorial1.pdf

It sounds like your DEM has at least one No Data Value. You can try setting the configuration option `NINJA_FILL_DEM_NO_DATA`. This will try to auto-fill the no data values. Note that setting this option will overwrite your DEM. To set the configuration option in the GUI go to Tools-->Set Configuration Option and set Option to NINJA_FILL_DEM_NO_DATA and Value to ON.

The above option won't work if there are too many No Data Values. There are often several rows/columns of No Data Values at the edges of the DEM after reprojection. If this is your issue, you could clip your DEM to get rid of the No Data Values. Or you could have WindNinja fetch a new DEM for you. See here:

http://firelab.github.io/windninja/pdf/download_elevation_file.pdf

**Comment by kiracool** [comment]
Thanks Natalie, I have Clipped my DEM and tried to run. But now it throws another exception saying that "Cells rectangular, not square outside of WindNinja's Threshold".
SRTM 90m DEM works fine which I downloaded using fetch data in GUI, But I want to try using the my DEM.

**Comment by nwagenbrenner** [comment]
WindNinja also requires that the DEM cells are square (dx=dy). It sounds like your DEM does not have square cells. You could resample your DEM to a resolution where dx=dy.

**Comment by kiracool** [comment]
My DEM cells are having square pixels, but I found the bug. It seems the method of clipping my DEM was throwing this exception. In QGIS, I was clipping the DEM by choosing extent, which was giving this error, but if I clip using some polygon(shape file) then it works. And also the DEM should be clipped in rectangular or square only.

**Comment by nwagenbrenner** [comment]
Okay, so you're able to successfully run the simulation with your DEM now? If so, I will close this issue. Please let us know if you have other questions.
