### ISSUE TITLE
Consider adding sub-hourly HRRR

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#240]

**Comment by ksshannon** [comment]
The time steps differ for temperature and u/v components.  It will take special handling in reading, so it isn't a drop in change for nomads.h.  It will likely need it's own wxModelInitialization sub class as well.

**Comment by nwagenbrenner** [comment]
The 10-m winds and 2-m T look to be on the same time steps here. Unless I'm missing something. Is it different on nomads? Why would that be?
  
https://rapidrefresh.noaa.gov/hrrr/HRRRsubh/Welcome.cgi?dsKey=hrrr_subh_jet
