### ISSUE TITLE
Update NAM data in nomads.h

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#244]
NAM is getting an upgrade:

http://www.nws.noaa.gov/om/notification/tin16-41nam_updatesaab.htm

The horizontal resolution will get finer for most models (maybe all), the times step of the output is changing for the NEST models, and some file names are begin changed.  The archived data goes from 28 days to 7, which will affect the past-cast branch.

The TIN is scheduled to be implemented March 15, 2017.   I believe this will break NAM models, but I have to test.

**Comment by ksshannon** [comment]
Non-exhaustive list:

- [ ] Alaska nest: change from the 6 km NDFD grid to the 3 km NDFD
- [ ] All NAM nests grids will be output hourly from 0-60 hour
- [ ] The NAM 12km CONUS grid #218 file will be renamed  nam.tCCz.awphysFF.grb2.tm00 -> nam.tCCz.awphysFF.tm00.grib2
- [ ] The number of days archived on the NCEP web services will be changed from 28 days to 7 days.

**Comment by ksshannon** [comment]
The TIN is postponed until March 15, 2017 due to Stella (the storm).

**Comment by ksshannon** [comment]
The build passed in the tin-16-41 branch.  With a little human testing, we can merge.  Question is, should we do #245 before the next release?  We probably don't want the NWS  models to be broken for too long.  Thoughts @nwagenbrenner, @jforthofer?

**Comment by nwagenbrenner** [comment]
We could merge the tin-16-41 branch and do a release (3.2.0) with this fix and #216. We could probably release it next week (assuming nothing comes up in the testing). How much work is #245? If it's ready, I think we should include it. If not, probably wait for the next release?

**Comment by ksshannon** [comment]
#245 may be as easy as un `#defining` some stuff.  If it is, I'll commit it, if not, we can wait.  Sound good?

**Comment by jforthofer** [comment]
Sounds good to me.

**Comment by nwagenbrenner** [comment]
Sounds good to me too.
