### ISSUE TITLE
NinjaElevationToStl fails on some Windows laptops

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#253]
Several IMET users reported run failures with the momentum solver that (based solely on the console output) appear to be due to failure during DEM conversion to STL format. There have been some recent security-related changes to IMET laptops, so this issue may be related to those changes. One IMET user reported that running WindNinja with admin privileges fixed the issue, but others reported no difference when running with admin privileges.

**Comment by ksshannon** [comment]
Ask if they can try setting CPL_TMPDIR to a writeable folder, maybe the output directory.

**Comment by nwagenbrenner** [comment]
We already set CPL_TMPDIR to be the location of the DEM, so I don't think that's the issue.

https://github.com/firelab/windninja/blob/master/src/ninja/ninjaArmy.cpp#L277

**Comment by jforthofer** [comment]
A non-IMET user may also be having this same problem.

**Comment by nwagenbrenner** [comment]
This was just reported by another user, this time on an FS laptop. I still can't replicate it.

**Comment by rnleach** [comment]
I noticed this while doing training with about 25 different people/laptops. We tried downloading a different DEM with roughly the same area, but it failed again. Others working in the same area had no problem. Then later when working in a different area (with less steep terrain) it worked for some users that it had not worked before. Very inconsistent. It's gone both ways on my laptop.
