### ISSUE TITLE
Enable GFS Hourly

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#254]
GFS now has hourly forecast for the first 240 hours.  I've prepared a change to make that the default, and the user has to opt in to the 3 hourly at compile time.  Should we just always make the highest resolution the default, and force the user to recompile for others, or expose all resolutions?

**Comment by nwagenbrenner** [comment]
I'd say make the highest resolution default. But that means if the user wants forecast hour 240, WindNinja will generate 240+ output files. Does that seem obnoxious? I guess once the start/stop/stride is implemented we won't have that issue though.

**Comment by ksshannon** [comment]
Yes, it is obnoxious, maybe we should change the output to write to a single kmz with all the kmls as layers.

**Comment by ksshannon** [comment]
That's another task though.

**Comment by nwagenbrenner** [comment]
Yeah, but we'll still have that issue for the other output formats. Probably the answer is the start/stop/stride?

**Comment by ksshannon** [comment]
Agreed.
