### ISSUE TITLE
Update shapefile docs

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#255]
It sounds like ArcView is no longer around/supported (according to Chuck)? Should we consider getting rid of the ArcView data and documentation? The ArcMap docs need to be reviewed/edited. Also, the shapefile docs aren't being packaged in the installer and so the links in the GUI are broken.

**Comment by jforthofer** [comment]
Yeah, that all sounds accurate to me, getting rid of ArcView data in the shapefile and documentation would be good.  Maybe we can talk Chuck into going over the ArcMap docs.

**Comment by ksshannon** [comment]
Looks like this is done?

**Comment by nwagenbrenner** [comment]
Chuck was editing the ArcMap instructions. When I get those, I'll commit them and close the ticket.
