### ISSUE TITLE
Handle colons in NetCDF filenames

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#263]
We can't handle colons in the filenames of NetCDF files. This is presumably because the NetCDF driver in GDAL can't handle colons in the filename due to the way it identifies sub-datasets within the file. It uses the following convention where colons are used to separate filename/variable names.

NETCDF:filename:variable_name

This is an issue for wrfout files, which commonly have colons in the filename as part of a timestamp to indicate when the run was initialized. We should try to handle this (by cleaning the filename string for example).

**Comment by ksshannon** [comment]
We can try escaping the quotes:

    gdalinfo NETCDF:"/home/kyle/Desktop/a:b:c.nc":Temperature_height_above_ground

doesn't work, but: 

    gdalinfo NETCDF:\"/home/kyle/Desktop/a:b:c.nc\":Temperature_height_above_ground

does...

**Comment by nwagenbrenner** [comment]
Actually, it looks like just adding quotes fixed the issue.
