### ISSUE TITLE
Problem building Windninja on Linux

### ISSUE THREAD

**Issue by aklibenali** [firelab/windninja#267]
Hi,

I am trying to build windninja on Linux Mint 18.2.  

When running ./build_deps.sh, I get an error when building "GDAL with poppler support". After "make -j 8", I get this:

/usr/bin/ld: /home/akli/windninja/scripts/gdal-2.0.3/frmts/o/.libs/aaigriddataset.o: relocation R_X86_64_32 against `_ZTV14AAIGRasterBand' can not be used when making a shared object; recompile with -fPIC
/home/akli/windninja/scripts/gdal-2.0.3/frmts/o/.libs/aaigriddataset.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [libgdal.la] Error 1
make: *** [check-lib] Error 2

Does anyone know how to fix this? 

I tried to ignore this, but when doing CMake some steps below, I get an error that I assume is related with the one showed above:

Could NOT find GDAL (missing:  GDAL_LIBRARY GDAL_INCLUDE_DIR) 

Thanks

**Comment by aklibenali** [comment]
The problem is solved by adding "make clean" to build_deps.sh, before "make -j 8"

**Comment by nwagenbrenner** [comment]
Glad it's working for you @aklibenali. Let us know if you run into any other issues.
