### ISSUE TITLE
How to use alternative Model Data for Initialization

### ISSUE THREAD

**Issue by aklibenali** [firelab/windninja#269]
Hi

I have weather forecasts in a 5km grid and want WindNinja to use them for initialization. I have the physical files, with a direction and speed file for each time step (i.e. one dir and one speed file for each hour).

The cli_wxModelInitialization_local_model.cfg  exemplifies how to do this reading a single netcdf file that has a very specific (and complex) structure.

My question if it is possible to run WindNinja using the files I mentioned above? Maybe the "Input_dir_grid" and "input_speed_grid" options could be used for this purpose, but I dont know.

THanks

**Comment by nwagenbrenner** [comment]
Yes, you can initialize WindNinja with gridded wind speed and direction. You need to use the `griddedInitialization` option in the CLI. This is a new feature and isn't yet described in the documentation. It also hasn't been tested much. To use this option, you'll have to supply your gridded wind speed and direction files in AAIGrid format. See attached for an example. Let us know if this works for you.

[griddedInit.zip](https://github.com/firelab/windninja/files/1376152/griddedInit.zip)

**Comment by aklibenali** [comment]
I am getting this error:

(...)
Run 0: Initializing flow...
Exception caught: Invalid cell reference in AsciiGrid<T>::get_cellIndex().
Exception caught: Invalid cell reference in AsciiGrid<T>::get_cellIndex().

My first guess is that the problem is due to the formatting of the wind speed\dir files. I am trying to understand what are the differences between your and my dir and speed files, but so far it is taking a very very long time to run WN with your CFG. Not sure if it is stuck or simply taking a long long time.

Akli

**Comment by nwagenbrenner** [comment]
The example I sent should run in seconds. I had a custom output path set in the config file. Did you update this to an existing directory on your machine (or just remove that option)?

If you send me your grids and cfg file, I can take a look.

**Comment by aklibenali** [comment]
Natalie,

It's working, I have no idea what I did to solve the problem. I just started from the beggining, using your cfg and step by step updating it with my files and settings. 

The original meteo model is 5km resolution, the  output  is 100m resolution with a 50 by 50 km grid. It took 80 seconds with 4 threads with the simpler solver.

Just curious: what is the reason behind for the "patchy" look in the lower right corner? 

The outputs and the original meteo files are here: https://drive.google.com/file/d/0B2riCCtlgseEV1E3Q2E4S21HU0U/view?usp=sharing

Thanks

**Comment by nwagenbrenner** [comment]
Can you also upload the DEM and cfg file you used?

**Comment by aklibenali** [comment]
I updated the compressed file, let me know if everything is ok.

Also, please feel free to give me any advice on how to improve the accuracy of WN wind fields.

Thanks

**Comment by aklibenali** [comment]
Finally I was able to reproduce the initial error. The problem is in the elevation file. The one that is in the compressed file works well: it's 100m res 50km by 50km grid. However, it does not cover completely the scar of the fire I am simulating.

I tried to use a 250m res 50km by 50km grid (attached) and I got the initial error "Exception caught: Invalid cell reference in AsciiGrid::get_cellIndex()."

Hope you can help.
[elevation_250m_100x100km_utm29n.tif.zip](https://github.com/firelab/windninja/files/1377332/elevation_250m_100x100km_utm29n.tif.zip)

**Comment by nwagenbrenner** [comment]
I haven't had a chance to look yet, but my first guess is that your input speed and direction grids do not completely cover the DEM. You'll need to have several cells that extend past the edges of the DEM (speed/dir grids slightly larger than the DEM) to ensure the DEM is completely covered after the grids are reprojected to the DEM projection.

**Comment by aklibenali** [comment]
Let me try that.

**Comment by aklibenali** [comment]
You were right, the problem was solved by using a speed/dir grid larger than the DEM, ensuring that the DEM is fully covered. 

However, the "patchy look" remains. If you see the wind speed output you'll notice that WN is not dealing well with the transitions between pixels, especially when these are abrupt. I attached also a printscrn in a particularly bad area.

![screenshot at 2017-10-12 15-53-44](https://user-images.githubusercontent.com/32641831/31502697-c48eee92-af65-11e7-91db-48f3c452ed3e.png)

[proenca_a_nova.zip](https://github.com/firelab/windninja/files/1379690/proenca_a_nova.zip)

**Comment by nwagenbrenner** [comment]
The patchy look was happening because we were using 0 order interpolation when interpolating the coarse model wind to the computational domain for initialization. I just changed it to use 1st order interpolation instead, so this should be fixed now in the master branch if you want to test it out. Let us know if this fixes the issue. Also, I didn't mention it before, but your DEM and input speed and direction grids need to be in the same projection. We can change this later to handle mixed projections, but currently we do not handle this for griddedInitalization.

**Comment by aklibenali** [comment]
Please tell me what switch you use to determine the order of the interpolation? I dont remember seeing that in the CLI documents.

The DEM and the Grids are in the same projection, the only problem is that the grids don't have the ".prj" file.

**Comment by nwagenbrenner** [comment]
The interpolation method is not settable by the user. The relevant change in the code is 7a1a6e6. We should have always been using 1st order interpolation here, it was a bug. Thanks for reporting the issue.

**Comment by aklibenali** [comment]
How to I integrate the changes you made in my WindNinja? From what you wrote it looks like this is possible "so this should be fixed now in the master branch if you want to test it out. Let us know if this fixes the issue.".

**Comment by nwagenbrenner** [comment]
Yes, you can just go into the directory where you installed the source code (the top level directory of the WindNinja source tree) and run the following command

`git pull`

This is will fetch the changes in the master branch and merge them into your local code. Then go to your build directory and run `make` again.

Let us know if you have questions and if the fix works for you.

**Comment by aklibenali** [comment]
Yes, it worked! But I had to follow all the instructions in the webpage, from "cmake" to "sudo make install". In other words, running just "make" does not solve the problem.

I am attaching a map just to show how smooth the final result is.

THanks again for your help Natalie.

![screenshot at 2017-10-14 15-16-34](https://user-images.githubusercontent.com/32641831/31576435-b43a23de-b0f2-11e7-87a2-b5535a04eff6.png)

**Comment by aklibenali** [comment]
Just a small comment: Using the cfg fie I sent you, that does not specify input and output speed units, the output is multiplied by a factor of ~2. I forced bohth input and output units to kph and I still get the same output. (the same with mph)

I found one way to solve this by setting kps units to input and output. I think this is a bug, just to let you know.

**Comment by nwagenbrenner** [comment]
Yes, that's another limitation of `griddedInitialization` right now. The input grid must be in mps. You can set the output units to any of the listed options, but the input speed grid must be in mps (setting the input speed units option has no effect on `griddedInitialization`). I can try to fix this next week.

**Comment by nwagenbrenner** [comment]
You should be able to supply the speed grid in any of the listed units now (mps, kph, mph, kts). To get the fix, you'll have to pull down the latest changes and rebuild WindNinja like before. Please reopen this issue if you find any other problems.

**Comment by aklibenali** [comment]
Hi

It looks like the "diurnal_winds" doesn't work when using the "griddedInitialization" using WN CLI. It does not give an error, it just gets stuck in "Run 0: Initializing flow...". Any ideas?

Here are some of my inputs:
num_threads			= 4
elevation_file             	= /home/akli/windninja/testing/elevation_100m_50x50km_utm29n.tif
initialization_method		= griddedInitialization
vegetation                      = trees
diurnal_winds                   = true
uni_air_temp 			= 30
air_temp_units  		= C
uni_cloud_cover 		= 0
cloud_cover_units 		= fraction
year 				= 2017
month 				= 7
day 				= 23
hour 				= 13
minute 				= 0
input_speed_units 		= mps
output_speed_units 		= mps
time_zone			= Europe/Lisbon
input_speed_grid                = /home/akli/windninja/testing/07-23-2017-1300h_wsp.spd
input_dir_grid                  = /home/akli/windninja/testing/07-23-2017-1300h_waz.dir
(...)

**Comment by nwagenbrenner** [comment]
The air temperature grid wasn't being set properly. I just fixed it in the master branch. Thanks for pointing this out. Let us know if you run into any other issues.

**Comment by aklibenali** [comment]
I updated windninja according your previous post (git pull + cmake again) and now the code runs. The problem is that there is no difference in the output wind speed. There is a very small diference in the wind angle (<1.5deg), with a very salt & pepper pattern

I made a test using the point average option using the same elevation file and same day, and there are relevant diferences in the outputs.

Here are my inputs:
num_threads			= 4
elevation_file             	= /home/akli/Work/Projects/FIRE-MODSAT/Data/Inputs/raster/dtm/aster/Abrantes_090817_BP1/100m/v1/elevation.asc
initialization_method		= griddedInitialization
vegetation                      = trees
diurnal_winds                   = true
uni_air_temp 			= 30
air_temp_units  		= C
uni_cloud_cover 		= 0
cloud_cover_units 		= fraction
year 				= 2017
month 				= 8
day 				= 9
hour 				= 20
minute 				= 0
input_speed_units 		= mps
output_speed_units 		= mps
time_zone			= Europe/Lisbon
input_speed_grid                = /home/akli/Work/Projects/FIRE-MODSAT/FARSITE/Inputs/wind/ua/Abrantes_090817_BP1/100m/mm5_2017080912_wninja/08-09-2017-2000h_wsp.spd
input_dir_grid                  = /home/akli/Work/Projects/FIRE-MODSAT/FARSITE/Inputs/wind/ua/Abrantes_090817_BP1/100m/mm5_2017080912_wninja/08-09-2017-2000h_waz.dir

(...)

**Comment by aklibenali** [comment]
I am sorry, there are differences in the windspeed but they are so small that they are imperceptible. Maximum diference between diurnal\no diurnal is ~0.2 kph.

Is the model performing as expected?

**Comment by nwagenbrenner** [comment]
The strength of the diurnal winds will depend on several things like incoming solar radiation, strength of the background wind, and the terrain. Depending on these things, it's possible your results are as expected.

**Comment by ncubukcu** [comment]
Just to add here for the shake of making griddedinitialization more widespread. I wanted to use .lcp file for  the elevation file input  but it hangs at reading elevation. 
Run 0: Reading elevation file...

Any idea on this? Thanks

Here is the cfg:

num_threads                     =   4
elevation_file                  =   test.lcp
initialization_method           =   griddedInitialization
input_speed_units=mps
vegetation                      =   grass
time_zone                       =   auto-detect
input_speed_grid                =   big_butte_small_0_2_123m_vel.asc
input_dir_grid                  =   big_butte_small_0_2_123m_ang.asc
input_wind_height               =   10
momentum_flag=true
number_of_iterations=200
units_input_wind_height         =   m
output_wind_height              =   10
units_output_wind_height        =   m
mesh_choice                     =   coarse
write_goog_output               =   true
output_path                     =   ./
