### ISSUE TITLE
Add tutorial cases

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#270]
In addition to our documentation, we could also supply some tutorial cases for CLI runs to demonstrate the different initialization options, etc. We already have a few cfgs in data/, but they don't cover a lot of the available options (e.g., griddedInitialization, specifying the output directory, requesting point output). It also might be better to have them in their own location (outside of data/). We could have a tutorial directory with sub-directories for broad categories (e.g, domainAverageInitialization, point, wx, gridded) and then multiple cases within each of these categories using different options. 

The cases would mostly just contain the cfgs, but some may also contain additional files, (e.g., a text file of extraction points to demonstrate how to extract output at specific x,y,z locations or a small script to download a WRF file for initialization). We can use DEMs from data/ and set the output directory to the case to keep the files contained/organized. 

It seems like this could be handy for new users or for demonstrating how to use new features.

**Comment by BastienFR** [comment]
+1 on tutorial for the cli runs.  So far, it's pretty hard to debug when this is the type of error message you get: `Exception caught: boost::bad_any_cast: failed conversion using boost::any_cast`.  Also, there should be more default value so user can simply select their DEM and their wind and it could work.  It's easier to build a command line from ground up without having to write dozens of options.  It reduce the risk of errors.  Also, having example helps understanding how to enter the inputs.  For exemple, in the GUI, you can add multiple wind speed and direction, but how can you do it in the CLI?  There are no examples I I still haven't figure it out.Anyhow, thanks for the nice program!

**Comment by nwagenbrenner** [comment]
Thanks for the comment @BastienFR. Hopefully we can get some tutorial cases included soon. 

We try to catch as many errors as possible and produce helpful error messages, but sometimes there are things we miss. We agree, it is frustrating to get errors like the one you mention. If you send us the configuration file which generated this error, we will try to handle it better.

We've tried to set as many default values in the command line as possible, but it would be confusing if we set default options for certain inputs. For example, it wouldn't make sense to have a default input speed set in cases where the user specifies the wxModelInitializaiton option. In case you haven't already found them, there are some example configuration files in the data/ folder of this repo which demonstrate a variety of initialization options and could be helpful. 

It is not possible to set up multiple domainAverageInitialization runs from the CLI. You could write a wrapper script to run multiple CLI runs though.

**Comment by BastienFR** [comment]
Thanks for you reply.  Far from me the idea to criticize your program, I just want to give my 2 cents on a user experience.  I did manage to get it to work so that's great.  

The error message I was getting was coming from the fact that I didn't add the  `--initialization_method domainAverageInitialization` in the system call.  Stupid mistake.  I understand your point about default values, it's true that it may be hard to set more of them considering all the interactions between the options.  Could it be possible to save a configuration file from the GUI just after running the model.  I checked and I couldn't find a way.  This could also help beginners as it is fairly easy to use the GUI.  I would just have to make the program work in the GUI for your needs once, than you get a configuration file that you can slightly modify to your need in the CLI.  

Anyway, for my needs, I don't use the configuration file, I go directly in the command line.  I use R which makes it easier to program.  That also allowed me to set up my own default values.

here is my preliminary script if you're interested: 
```
wind_ninja <- function(num_threads=1, elevation_file, input_speed, input_speed_units="kph", output_speed_units="kph",
                  input_direction, input_wind_height=10, units_input_wind_height="m",
                  output_wind_height=10, units_output_wind_height="m", vegetation,
                  mesh_resolution, units_mesh_resolution="m", 
                  output = c("write_ascii_output", "write_wx_model_ascii_output"),
                  output_path = NULL, momentum_flag = NULL,
                  initialization_method = "domainAverageInitialization"){
  command <- paste(
    "C:/WindNinja/WindNinja-3.3.0/bin/WindNinja_cli.exe",
    "--num_thread", num_threads, 
    "--elevation_file", elevation_file, 
    "--input_speed", input_speed,
    "--input_speed_units", input_speed_units,
    "--output_speed_units", output_speed_units,
    "--input_direction", input_direction,
    "--input_wind_height", input_wind_height,
    "--units_input_wind_height", units_input_wind_height,
    "--output_wind_height", input_wind_height,
    "--units_output_wind_height", units_input_wind_height,
    "--vegetation", vegetation,
    "--mesh_resolution", mesh_resolution,
    "--units_mesh_resolution", units_mesh_resolution,
    paste(paste(paste0("--", output), collapse = " true "), "true"),
    ifelse(is.null(output_path), "", paste0("--output_path ",output_path)),
    ifelse(momentum_flag==T, "--momentum_flag true", ""),
    "--initialization_method", initialization_method,
    sep = " "
  )
 
 system(command) 
}
```

It's not completed and doesn't take into account all options, but it works great for my needs so far and will allow me to easily call multiple wind speeds and directions.  

Thanks again for your program.

**Comment by nwagenbrenner** [comment]
@BastienFR glad you've got things working now. Good suggestion about saving a configuration file from a GUI run. This is on our wish list, #24.

**Comment by alcliberal** [comment]
Hello! I have the same error `Exception caught: boost::bad_any_cast: failed conversion using boost::any_cast` when I try to download the terrain file from windNinja.
my .cfg is attached

num_threads=1
x_center=48.1498753
y_center=0.3560498
x_buffer=10
y_buffer=10
buffer_units=km
elevation_source=world_srtm
mesh_choice=coarse
mesh_resolution=500
units_mesh_resolution=m
time_zone=Europe/Paris
year=2021
month=3
day=5
hour=7
minute=0
diurnal_winds=False
non_neutral_stability=False
initialization_method=wxModelInitialization
wx_model_type=NOMADS-GFS-GLOBAL-0.25-DEG
forecast_duration=3
vegetation=grass
momentum_solver=True
number_of_iterations=300
output_speed_units=kts
output_wind_height=30.0
units_output_wind_height=m
write_pdf_output=True
write_vtk_output=True

**Comment by alcliberal** [comment]
> 
> 
> Hello! I have the same error `Exception caught: boost::bad_any_cast: failed conversion using boost::any_cast` when I try to download the terrain file from windNinja.
> my .cfg is attached
> 
> num_threads=1
> x_center=48.1498753
> y_center=0.3560498
> x_buffer=10
> y_buffer=10
> buffer_units=km
> elevation_source=world_srtm
> mesh_choice=coarse
> mesh_resolution=500
> units_mesh_resolution=m
> time_zone=Europe/Paris
> year=2021
> month=3
> day=5
> hour=7
> minute=0
> diurnal_winds=False
> non_neutral_stability=False
> initialization_method=wxModelInitialization
> wx_model_type=NOMADS-GFS-GLOBAL-0.25-DEG
> forecast_duration=3
> vegetation=grass
> momentum_solver=True
> number_of_iterations=300
> output_speed_units=kts
> output_wind_height=30.0
> units_output_wind_height=m
> write_pdf_output=True
> write_vtk_output=True

SOLVED

**Comment by Porkking** [comment]
I also met this warning when I want to run the cli by using the following file. Could you help me with it? I would like to use a specific time in WRF simulation to run the model. Thanks.
num_threads                     = 1
elevation_file                  = /home/zongrun/Desktop/Running/Fort_Benning_CLI/fort_benning.lcp
initialization_method           = wxModelInitialization
momentum_flag                   = true
number_of_iterations            = 2000
mesh_choice		        = fine
time_zone                       = Europe/London
forecast_filename               = /home/zongrun/Desktop/Running/Fort_Benning_CLI/wrfout_d03_2021-01-08.nc
forecast_time                   = 20210108T000000
diurnal_winds                   = true
write_goog_output               = true
write_shapefile_output          = false
write_ascii_output              = false
write_farsite_atm               = false

**Comment by nwagenbrenner** [comment]
Related issue #433. These tutorial cases should have README files that describe the functionality and any info that might  be confusing to the user. They could also contain scripts if needed, for example to download a wrfout or archived HRRR file to run a case. I think these should be contained in a folder outside of `data`. Maybe a new folder called `tutorial` or `cases`. They should be designed so that all output files are written to the local directory from where the case cfg is run. This may mean copying elevation files from `data` as a part of the example workflow so the `data` directory isn't polluted with output (e.g., NINJAFOAM case writing, etc. which always occurs in the same folder as the DEM).

**Comment by nwagenbrenner** [comment]
Tutorial framework and initial tutorials added in 9983096.
