### ISSUE TITLE
Fix point pointinialization/station-fetch segfaults

### ISSUE THREAD

**Issue by tfinney9** [firelab/windninja#271]
Some of the point initialization stuff broke when we changed some of the station-fetch code back in May. I've nearly fixed most of it right now.

**Comment by nwagenbrenner** [comment]
This is a separate issue from #265? Make sure you've pulled in the commits linked to that ticket.

**Comment by tfinney9** [comment]
It may be related to #265 I just  out text.txt attached in #265 and I was not able to reproduce a segfault, however I do not know why. I will continue to look into it.

**Comment by ksshannon** [comment]
Tanner, that bug is fixed.  I just didn't close it until it was ready to merge...

**Comment by ksshannon** [comment]
If I can reproduce, I'll fix it.  Attach a new config if needed.

**Comment by tfinney9** [comment]
I've fixed this now as far as I know with 5ea3e63
