### ISSUE TITLE
Corrections for dust and water vapor can result in negative surface radiation values

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#277]
This correction (where a2 = -30.0 from Holtslag and Ulden) can result in negative values for incident solar radiation.

https://github.com/firelab/windninja/blob/master/src/solar_grid/solar_grid.cpp#L260

https://github.com/firelab/windninja/blob/master/src/ninja/cellDiurnal.cpp#L314

If cells are shaded, Qsw = -30.0. Is this intended, or should 0.0 be the smallest value possible for Qsw?

**Comment by jforthofer** [comment]
I reread Van Ulden and Holtslag 1985 again, and yes, basically we should put a limiter on the Qsw so it doesn't go below 0.0.

From the paper:
The application of this equation is limited to solar angles greater than 1.7 degrees.  For smaller values Qsw should be set equal to zero.
