### ISSUE TITLE
Allow user to select lead time when using model data.

### ISSUE THREAD

**Issue by rnleach** [firelab/windninja#285]
When using model initialization, allow the user which lead times to do the forecast for. If I want to look at a specific event, maybe 24 or 48 hours out in the model, it would be nice if I didn't have to run forecasts for all the other model lead times. 

This is especially important for the Conservation of Mass and Momentum solver which can take a very long time to run.

**Comment by nwagenbrenner** [comment]
@rnleach thanks for the suggestion. We've got it on this list: #49.

**Comment by rnleach** [comment]
Yes, that would be great.

**Comment by ksshannon** [comment]
Folding into #49
