### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by rnleach** [firelab/windninja#288]
When Momentum Solver fails, the simulation just quickly runs to 100%, but there is an error reported. This is very confusing, because it looks like it worked, unless you look in the console.

**Comment by nwagenbrenner** [comment]
I can't replicate this one. There must be some problem early on in the simulation that we're not detecting. Maybe a write permission issue (seems like we had some of those on NWS laptops before). We need a way to replicate this one for testing.

**Comment by rnleach** [comment]
I haven't run into this in a really long time, so I'll close the issue. It probably was on of the many permissions issues we've had with those laptops.
