### ISSUE TITLE
Create an LCP download service

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#290]
The EROS download service is painfully slow.  With a little work, I think we can create our own, and host it.  I don't think the traffic will be terrible, so a small server will do.  We can fall back on the EROS service on failure.  We'd have to get the data shipped to us and loaded some how.  That might be the biggest head ache.

This can be done substantially easier if GDAL adds write/update/create support for the LCP driver, which I will investigate.

**Comment by nwagenbrenner** [comment]
I think I have the data. I think I got it from Don a while back. I'll check and report back. What are you thinking for the server? We could use our weather.firelab.org server. Or yours. Or something else. Whatever's best.

**Comment by ksshannon** [comment]
How big is the dataset?  Is it easy to get it onto your server?  I have upload limits on mine right now.

**Comment by nwagenbrenner** [comment]
I'll have to double check what data I actually got from Don and the size, but it shouldn't be an issue to put it on our server. weather.firelab.org is an instance in an OpenStack setup Bryce is running. I'll check on this stuff tomorrow.

**Comment by nwagenbrenner** [comment]
Yeah, that's a good idea. I guess the only concern is that we don't know how long the AWS server will be around. But if it goes away we'll have to move WindNinja Mobile (probably to our OpenStack server) anyway, so we could migrate everything at that time. Makes sense to use the same data server for mobile and desktop WindNinja. @ksshannon @jforthofer?

**Comment by nwagenbrenner** [comment]
Related issue firelab/windninja-mobile#113

**Comment by nwagenbrenner** [comment]
We have a source now, see #459.
