### ISSUE TITLE
Set wx station height AGL from station metadata 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#294]
Right now, the height AGL is hard-coded to 10 m (for both RAWS and ASOS). Two height variables are available in the station header data: 

1. `elevation_dem` which, based on the values,  is _maybe_ the ground elevation at the station location ASL (?)
2. `elevation` which, based on the values, is _maybe_ the height of the station AGL + ground elevation ASL (?) 

We need to verify what these variables are and if they are reported for all stations. If we can't get reliable station height AGL from the station data, we should set the height AGL to the nominal heights for each station type (e.g., RAWS, ASOS, etc.).

**Comment by jforthofer** [comment]
Also remember that there are at least 2 possible heights for RAWS (that I know of).  The permanent RAWS are all 20 ft I believe, and the "fire RAWS" are 6 ft masts I think.  So it might be hard to figure this out for RAWS if we can't find it in some metadata somewhere for the station.  If you guys can't figure this out, let me know and I can call a friend of mine that is one of the RAWS techs that travels around the country all year servicing permanent RAWS and installing fire RAWS.

**Comment by tfinney9** [comment]
added with 
614cc781959af4b531367dbf0989507004d1c237
