### ISSUE TITLE
Add communication from "phone home server"

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#295]
We should add the ability to communicate at GUI start-up via the phone home server. This would allow us to notify users when new versions of WindNinja become available or when critical bugs pop up.

**Comment by ksshannon** [comment]
Right now, I think I'll have an endpoint that provides the most recent version from querying github releases, and an arbitrary message that is usually empty.  The GUI will check its own version against what it gets back, and opens a pop up if the version is newer on the server.  If the message is not empty, it will be displayed after the version message if it exists.

**Comment by ksshannon** [comment]
Any thoughts on a format here?  JSON isn't exposed in GDAL, so that'd be tough, may simple key=value pairs?

**Comment by fspataro** [comment]
Some thoughts below, I can add some more detailed architecture/system design  -- sort of my specialty:

If you want to work in Python, go with the Flask API project.  It's the base for the mobile server.  Really easy to use and create endpoints, process inputs and outputs.  JSON support is built in, etc.  You can probably use the mobile "web" side right up.  

In theory the server-side component for the mobile already has a web endpoint, hosting, build, deployment implemented.  It'd be pretty easy to add this method there and then you get a consolidated "wind ninja server" without having multiple deployments.  All the apps (desktop mobile etc) can connect there.  

If you have to use GDAL (not sure i understand why), you can use the GeoJSON format just use null for the geometry attribute, it should still process the structure correctly.

**Comment by nwagenbrenner** [comment]
@ksshannon your plan sounds good to me and I don't have a preference on format. I'm good with whatever you think makes the most sense.

**Comment by ksshannon** [comment]
> If you want to work in Python, go with the Flask API project. It's the base for the mobile server. Really easy to use and create endpoints, process inputs and outputs. JSON support is built in, etc. You can probably use the mobile "web" side right up.

I already have a running server written in Go, I plan on ditching the unused portion and supporting the message handling, the visit handling, and what ever reports are required (separate ticket).

> If you have to use GDAL (not sure i understand why), you can use the GeoJSON format just use null for the geometry attribute, it should still process the structure correctly.

We only need GDAL to handle parsing the response.  I won't add a dependency for that.  That's the only constraint.

**Comment by ksshannon** [comment]
Implemented GUI/core side, I'll upload a server tomorrow.

**Comment by ksshannon** [comment]
Server added in f66204631259503c997518c2df8583b8cbe13bc7

Ancillary fix in 422ade1ab6c7c14d0fc28718ef8922f59718160c

**Comment by nwagenbrenner** [comment]
@ksshannon is it possible to display the message after the splash screen and GUI have loaded? And just have the GUI "frozen" until the message is dismissed.

**Comment by ksshannon** [comment]
It's possible, but can you explain why?  Do you like it better?  I am just curious.

**Comment by nwagenbrenner** [comment]
Yes, I would like it better. Right now it seems possible that it could get "lost" on a user's desktop. It confused me when it popped up and I hadn't seen the splash screen yet.

**Comment by ksshannon** [comment]
@nwagenbrenner I moved it after the splash, before the GUI starts, assuming QT signal/slots act in order.  Check it and let me know if it works.

**Comment by nwagenbrenner** [comment]
Reopening for implementation with the new phone home protocol.

**Comment by nwagenbrenner** [comment]
Completed in fb8512f4ae2bd49a7c327e8511776f16ab1a407d. See https://github.com/firelab/wns for server-side implementation details.
