### ISSUE TITLE
Print out config options to CLI

### ISSUE THREAD

**Issue by tfinney9** [firelab/windninja#297]
Add some sort of option to list out all available config options to the CLI.

**Comment by jforthofer** [comment]
Is this different than doing "--help"?

**Comment by nwagenbrenner** [comment]
Yes, these are options set, for example, by Tools->Set Configuration Option in the GUI. It includes these

https://github.com/firelab/windninja/wiki/Advanced-Runtime-Configuration

**Comment by ksshannon** [comment]
These are sort of hidden for a reason.  Mostly to avoid complexity.  99% of users should never know about these.  I don't oppose it, but I don't think we should burden people with confusion.  Most of them are for debugging and experimental reasons anyway, and should be deprecated.  I am all for a separate command line option (hidden?) to show these.  Maybe `--help-config`?  We will also need a good way to manage this stuff.  Maybe something in ninja_init...

**Comment by nwagenbrenner** [comment]
Yeah, a CLI option like you mentioned is what we're thinking. Like you said, these are useful for debugging and it's hard (for me) to remember them all.

**Comment by tfinney9** [comment]
Added with 473458f44e6b4d71a2d685a9dcab51e8d392c2a0

**Comment by ksshannon** [comment]
We need to come up with a way (documentation or checking in the code somewhere) of adding new options...
