### ISSUE TITLE
Prevent point initialization simulations when all stations report zero wind speed

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#304]
If the domain is filled completely with zeros (all stations reporting no wind), we should cancel the simulation and report the issue to the user.

**Comment by jforthofer** [comment]
If all stations report valid 0 mph winds, WindNinja should spew out wind grids with all zeros probably.  This comes from issues we've had before, especially if someone is running an automated type set of simulations.  If I remember correctly, somewhere in WindNinja there is a check for a domain average run of zero and grids of all zero are spit out.

**Comment by jforthofer** [comment]
Yeah,  I'm saying we should just generate grids with all zeros.  I'm 99%sure we do that for domain average.  The zero grids are sometimes useful for fire behavior simulations.  I think you can find in the code somewhere how we do it for domain average.  It doesn't actually do a simulation,  just writes grids with zeros.

**Comment by nwagenbrenner** [comment]
Okay, then I think we're good.
