### ISSUE TITLE
Test 3.4.0

### ISSUE THREAD

**Issue by tfinney9** [firelab/windninja#306]
- [x] Run autotest suite
- [x] Surface Data
  - [x] Download LCP from CONUS
  - [x] Download LCP from Alaska
  - [x] Download LCP from Hawaii
  - [x] Download US SRTM
  - [x] Download US SRTM outside of CONUS, expected fail
- [x] All runs below with all outputs turned on
- [x] Weather Models
  - [x] Run WindNinja from a directory other than C: and download nomads files
  - [x] Weather model run with diurnal on
  - [x] Weather model runs with all wx models
  - [x] Alaska weather model runs
- [x] Run a Point Initialization simulation
   - [x] Download Timeseries from Mesonet API
   - [x] Download Single time step from Mesnonet API
   - [x] Download weather stations by name from the Mesonet API
   - [x] Download weather stations from the DEM
   - [x] Fetch Metadata
   - [x] Run Point Initialization with multiple time steps
   - [x] Test direct point solver 
- [x] Domain Average Runs
  - [x] Mass conserving solver
  - [x] Mass conserving solver w/ diurnal
  - [x] Mass conserving solver w/ diurnal and stability
  - [x] Mass and momentum conserving solver
  - [x] Mass and momentum conserving solver w/ diurnal
  - [x] Multiple mass conserving solver w/ diurnal
  - [x] Multiple mass and momentum conserving solver w/ diurnal
  - [x] Mass and momentum conserving solver w/ existing case
- [x] Test metric units and wind heights
  - [x] Domain average run w/ diurnal
  - [x] Point initialization run
  - [x] Weather model initialization run
- [x] Test multiple processors
  - [x] Mass conserving solver
    - [x] Domain average run w/ diurnal
    - [x] Point initialization run
    - [x] Weather model initialization run
  - [x] Mass and momentum conserving solver
    - [x] Domain average run
    - [x] Domain average run w/ diurnal
- [x] Test documentation from Help menu
- [x] Is About page correct
- [x] Are version numbers correct
- [x] Do a CLI run

**Comment by tfinney9** [comment]
# Test 3.4.0 On Windows

- [x] Run autotest suite
- [ ] Surface Data
  - [x] Download LCP from CONUS
  - [x] Download LCP from Alaska
  - [x] Download LCP from Hawaii
  - [x] Download US SRTM
  - [x] Download US SRTM outside of CONUS, expected fail
- [ ] All runs below with all outputs turned on
- [ ] Weather Models
  - [ ] Run WindNinja from a directory other than C: and download nomads files
  - [x] Weather model run with diurnal on
  - [x] Weather model runs with all wx models
  - [x] Alaska weather model runs
- [ ] Run a Point Initialization simulation
   - [x] Download Timeseries from Mesonet API
   - [x] Download Single time step from Mesnonet API
   - [x] Download weather stations by name from the Mesonet API
   - [x] Download weather stations from the DEM
   - [x] Fetch Metadata
   - [x] Run Point Initialization with multiple time steps
   - [ ] Test direct point solver 
- [ ] Domain Average Runs
  - [x] Mass conserving solver
  - [x] Mass conserving solver w/ diurnal
  - [x] Mass conserving solver w/ diurnal and stability
  - [x] Mass and momentum conserving solver
  - [x] Mass and momentum conserving solver w/ diurnal
  - [x] Multiple mass conserving solver w/ diurnal
  - [x] Multiple mass and momentum conserving solver w/ diurnal
  - [x] Mass and momentum conserving solver w/ existing case
- [x] Test metric units and wind heights
  - [x] Domain average run w/ diurnal
  - [x] Point initialization run
  - [x] Weather model initialization run
- [x] Test multiple processors
  - [x] Mass conserving solver
    - [x] Domain average run w/ diurnal
    - [x] Point initialization run
    - [x] Weather model initialization run
  - [x] Mass and momentum conserving solver
    - [x] Domain average run
    - [x] Domain average run w/ diurnal
- [ ] Test documentation from Help menu
- [ ] Is About page correct
- [x] Are version numbers correct
- [x] Do a CLI run

**Comment by ksshannon** [comment]
@tfinney9 @nwagenbrenner can we close 3.4.0?
