### ISSUE TITLE
Allow setting the 'messages' for the phone home server

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#315]
After #295, we need to implement a way for core users to set and clear messages.  Messages also have to persist over server restarts.  I'll tack on a plan when I get a chance.

**Comment by fspataro** [comment]
WindNinja Server has a "notification" system you can loosely follow.  It uses a "message" store -  right now it's a folder of json files but that structure could easily be loaded to any database.  The message has an start and end property.  The API controller filters messages that are inside the event time on each request.

**Comment by nwagenbrenner** [comment]
Related to #481
