### ISSUE TITLE
decomposePar error

### ISSUE THREAD

**Issue by Saszalez** [firelab/windninja#317]
Hello. I'm trying to execute the sample files. I've tried it with a simple example (cli_domainAverage.cfg). The test case worked well both in 1 thread and in 4. So, I tried to run a more complex example (cli_momentumSolver_diurnal.cfg). I get the following error:

`Run 0: Decomposing domain for parallel mesh calculations...`

`Run 0: Decomposing domain for parallel mesh calculations...`
`ERROR 1: [decomposePar error]`

`--> FOAM FATAL IO ERROR:`
`Essential entry 'value' missing`

`file: /home/ulpgc/windninja/etc/windninja/example-files/NINJAFOAM_missoula_valley3547351360_1/0/epsilon.boundaryField.west_face from line 41 to line 47.`

    `From function Foam::fvPatchField<Type>::fvPatchField(const Foam::fvPatch&, const Foam::DimensionedField<Type, Foam::volMesh>&, const Foam::dictionary&, bool) [with Type = double]`
   ` in file /home/ulpgc/openfoam/OpenFOAM-6/src/finiteVolume/lnInclude/fvPatchField.C at line 131.`

`FOAM exiting`

`WindNinja_cli: /home/ulpgc/windninja/source/windninja/src/ninja/Array2D.h:438: const T& Array2D<T>::operator()(unsigned int, unsigned int) const [with T = double]: Assertion 'row <= rows || col <= cols' failed.`
`Aborted (core dumped)`

**Comment by latwood** [comment]
This almost sounds like you are using OpenFOAM of a later version than what
comes with the WindNinja distribution. Either that or one of epsilon file
for the time 0 of the momentum solver didn't write correctly as it might
specify values but forgot the definition keyword "value" for the set of
values.

The older versions of OpenFOAM were less picky about this entry.

Anyhow I don't officially work at the fire lab anymore so I'll let one of
the others handle this, but just thought I'd throw my two cents out there
cause I used to work with the OpenFOAM stuff in WindNinja a lot.

**Comment by nwagenbrenner** [comment]
@Saszalez you're using OpenFOAM 2.2.x? Can you zip up NINJAFOAM_missoula_valley3547351360_1 and send it to me? I'll take a look.

**Comment by Saszalez** [comment]
@nwagenbrenner I am using a later version. Version 2.2.2 gives me problems when building it. When I try to build Paraview I get the following error:

`*** Error: can not find qmake either at $ QMAKE_PATH or in current $ PATH`

I have established the path but Paraview can not find it.

I have also followed the instructions of the OpenFOAM Wiki: https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-2.2.2/CentOS_SL_RHEL

But it also gives an error when trying to build gmp-5.0.1

**Comment by nwagenbrenner** [comment]
You will definitely have to use 2.2.x with our code. You can get away without building ParaView, but you will need to compile our custom OpenFOAM libraries and applications described at the bottom of the page here

https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Linux

If you compile OpenFOAM 2.2.x and our custom OpenFOAM code, and the following commands generate the usage info, then you are probably good.

    blockMesh -help
    applyInit -help

**Comment by Saszalez** [comment]
@nwagenbrenner Hello again. I have managed to build OpenFOAM 2.2.2. 
```
blockMesh -help

Usage: blockMesh [OPTIONS]
options:
  -blockTopology    write block edges and centres as .obj files
  -case <dir>       specify alternate case directory, default is the cwd
  -dict <file>      specify alternative dictionary for the blockMesh description
  -noFunctionObjects
                    do not execute functionObjects
  -region <name>    specify alternative mesh region
  -srcDoc           display source code in browser
  -doc              display application documentation in browser
  -help             print the usage

Using: OpenFOAM-2.2.2 (see www.OpenFOAM.org)
Build: 2.2.2-9739c53ec43f
```

But I still get the same error as before.

```
./WindNinja_cli ../../etc/windninja/example-files/cli_momentumSolver_diurnal.cfg 
Run 0: Reading elevation file...
Run 0: Run number 0 started with 4 threads.
Run 0: Writing OpenFOAM files...
Run 0: Converting DEM to STL format...
Run 0: Transforming surface points to output wind height...
Run 0: Generating mesh...
Run 0: Running blockMesh...
Run 0: Decomposing domain for parallel mesh calculations...
ERROR 1: [decomposePar error] 

--> FOAM FATAL IO ERROR: 

    Cannot find 'value' entry on patch west_face of field k in file "/home/ulpgc/windninja/etc/windninja/example-files/NINJAFOAM_missoula_valley2899138880_1/0/k"
    which is required to set the values of the generic patch field.
    (Actual type logProfileTurbulentKineticEnergyInlet)

    Please add the 'value' entry to the write function of the user-defined boundary-condition


file: /home/ulpgc/windninja/etc/windninja/example-files/NINJAFOAM_missoula_valley2899138880_1/0/k.boundaryField.west_face from line 41 to line 47.

    From function genericFvPatchField<Type>::genericFvPatchField(const fvPatch&, const Field<Type>&, const dictionary&)
    in file genericFvPatchField/genericFvPatchField.C at line 71.

FOAM exiting

Run 0: Error during decomposePar().
Run 0: Error during moveDynamicMesh().
Run 0: Error setting up new OpenFOAM case
Run 0: Reading elevation file...
Run 0: Simulation time is 2011-Sep-23 13:30:00 MDT
Run 0: Run number 0 started with 4 threads.
Run 0: Generating mesh...
Run 0: Initializing flow...
WindNinja_cli: /home/ulpgc/windninja/source/windninja/src/ninja/Array2D.h:438: const T& Array2D<T>::operator()(unsigned int, unsigned int) const [with T = double]: Assertion `row <= rows || col <= cols' failed.
Aborted (core dumped)

**Comment by latwood** [comment]
Yeah Natalie, I think all I had to do when using WindNinja OpenFOAM 2.0.x
stuff with OpenFOAM 4.0.x stuff was add this entry, technically it should
be there even for the OpenFOAM 2.0.x stuff, but that version let you get
away with not having that entry saying the following values are values.

So I think it is a simple fix, either use OpenFOAM 2.0.x so that the files
WindNinja writes are compatible, or maybe need to mess with the way
WindNinja writes the files to add this entry. At least I think that was all
I had problems with when switching versions. There may have been more. So
probably safest to just use the same OpenFOAM version as the files
WindNinja writes.

**Comment by nwagenbrenner** [comment]
@Saszalez Are you sure the custom libraries and applications were built properly? What does 

    which applyInit

return? If you zip up the NINJAFOAM* case file and send it to me, I will take a look.

**Comment by nwagenbrenner** [comment]
This seemed to be an OpenFOAM installation issue.
