### ISSUE TITLE
NOMADS: replace AutoCreateWarpedVRT with full GDALWarper semantics

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#321]
In the past, large GRIB files with many bands chew up a lot of cycles warping all the bands.  This was temporarily alleviated in AutoCreateWarpedVRT in GDAL, and it had to be backed out.  We should add a function very similar to AutoCreateWarpedVRT, but that handles subsetting of bands (and possibly in X/Y?).  This should help with some GRIB files that aren't pre-subsetted in space, and may allow for `/vsicurl` calls where `grib filter` is not implemented in NOMADS (requires GDAL 2.3.0+).

**Comment by ksshannon** [comment]
@nwagenbrenner when you get a chance, can you send me a test file?  Thanks.

**Comment by nwagenbrenner** [comment]
@ksshannon I think you can get what you need from U of Utah archive with

wget https://pando-rgw01.chpc.utah.edu/hrrr/prs/20160801/hrrr.t00z.wrfprsf00.grib2

http://home.chpc.utah.edu/~u0553130/Brian_Blaylock/hrrr_script_tips.html

Our HRRR initialization should be able to work with these.
