### ISSUE TITLE
WindNinja can't find leaflet directory on Windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#323]
The map doesn't load because it's not finding the leaflet directory. Do we need to do something about the paths in map.htm?

**Comment by ksshannon** [comment]
This is tough for me to test.  I thought the paths in map.htm are relative to where map.htm is at, but maybe it needs to be something else.  What does the directory structure look like after it's installed?

**Comment by nwagenbrenner** [comment]
map.htm and leaflet/ are both in share/windninja.

![image](https://user-images.githubusercontent.com/3696653/47236888-aadf8600-d39a-11e8-8261-5f84f977c28b.png)

**Comment by nwagenbrenner** [comment]
It looks like the full path is required on Windows for some reason. For example, this works:

    <link rel="stylesheet" href="C:/WindNinja/WindNinja-3.4.0/share/windninja/leaflet/leaflet.css"/>

but this doesn't

    <link rel="stylesheet" href="leaflet/leaflet.css"/>

even though leaflet/ is in the same directory as map.htm.

**Comment by fspataro** [comment]
if we can figure out where the browser windows thinks it's rooted... we might be able to figure out the correct relative path syntax.  Can you open the developer console with the non-functional window?  If so try evaluating the following:

window.location 
window.location.href
window.location.origin
window.location.pathname

Those should spit back the current browser window root.

**Comment by nwagenbrenner** [comment]
The leading ./ didn't fix it. 

On Windows:

window.location.href = "c:\WindNinja\WindNinja-3.4.0\bin\../share/windninja\map.htm"
window.location.origin = "c://"
window.location.pathname = "\WindNinja\WindNinja-3.4.0\bin\../share/windninja\map.htm"

On Linux:

window.location.href = "file:///home/natalie/src/windninja/data/map.htm"
window.location.origin = "file://"
window.location.pathname = "/home/natalie/src/windninja/data/map.htm"

**Comment by fspataro** [comment]
When I open the map.htm file locally, the browser clearly uses the "file://" protocol and the map displays correctly - which matches what linux is doing.  How are you loading the map.htm file to browser are you using the file protocol?

Couple things to try:
* Try using the file:// protocol to load the html file initially
* It could be the ".." and mixed path separator slashes.  Could try to "resolve" that path rather than using the .. inside it.

**Comment by nwagenbrenner** [comment]
Appending file:// to the path when map.htm is loaded seems to fix it. I think we're good now. I'll commit the change.
