### ISSUE TITLE
Incorrect units in station kml output

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#325]
If you do a point initialization run, and check the box to "Write Station Kml", the units in the station kml file seem to always be in meters per second and degrees C.  It would be best if they were output in the same units as the other output files (at least the speed units), which is defined in the GUI by the user under "Output" and then "Output Speed Units".

**Comment by nwagenbrenner** [comment]
So you want to leave temperature (and height of the measurement) in the base units, but report the wind speed in the same units as requested for the output? Just want to double check before I change anything. Right now we are reporting both speed and temperature in base units. Seems logical to have all three (height, wind speed, temperature) in either metric or english units.

**Comment by jforthofer** [comment]
Yeah, I think the user has control from the GUI "Output" panel of the speed units and output wind height units, but not temperature.  Not sure how you'll resolve this for temperature, but maybe just use the temperature units that correspond to the user's choice of speed units (metric or english)?  Or put a temperature unit choice in the GUI, but that would require a little more work I suppose.  I don't care either way, what do you think?
