### ISSUE TITLE
Error downloading some GMTED and World SRTM data

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#328]
An Australian user reported this. You get the following errors when you try to download GMTED or World SRTM data from some areas. It seems to be intermittent, so it's hard to figure out what's going on. This might only by happening on Windows.

ERROR 6: EPSG PCS/GCS code 32691 not found in EPSG support files. Is this a valid EPSG coordinate system?
ERROR 6: No translation for an empty SRS to PROJ.4 format is known

**Comment by ksshannon** [comment]
Can you send me a bounding box.  That is an invalid SRS number.

**Comment by ksshannon** [comment]
Please try master.

**Comment by ksshannon** [comment]
I'll test a few more edge cases later.

**Comment by nwagenbrenner** [comment]
I can't replicate this error in the master branch. It looks like it might be fixed?
