### ISSUE TITLE
NOMADS downloading is broken

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#329]
All of the NOMADS downloads failed last night and are still failing. The NOMADS webpage (nomads.ncep.noaa.gov) is what's being downloaded into NINJA_FCST*.zip. Did maybe the grib filter change? The request we send has this:

&dir=/hrrr.20190206/conus

but if you test the grib filter from the NOMADS webpage the &dir portion looks like this (not sure what the %2F is?):

&dir=%2Fhrrr.20190206%2Fconus

**Comment by CoasterBGW** [comment]
NOMADS moved to HTTPS only yesterday. 

https://www.nco.ncep.noaa.gov/pmb/changes/URL_http_https.shtml

 https://www.weather.gov/media/notification/scn18-100ncep_urlsaae.pdf

**Comment by nwagenbrenner** [comment]
Yeah, https is the issue. I thought that move had already happened.

Is it just the urls in nomads.h that need to be updated @ksshannon? I can push the fix and do a build for a new release.

**Comment by ksshannon** [comment]
@nwagenbrenner, yeah, just add the `s` in nomads.h.  I thought they'd redirect, but maybe the curl client in gdal doesn't have that enabled by default.

**Comment by nwagenbrenner** [comment]
Fixed in 3c4d77b.
