### ISSUE TITLE
Seg fault when doing multiple domain average runs from the GUI.

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#33]
WindNinja blows up when you do multiple domain average runs from the GUI.  This occurs when you hit solve.  On Windows.

**Comment by ksshannon** [comment]
fixed in 0c1b7bebe19b6afb07d34e76bc726a80d997763f

**Comment by ksshannon** [comment]
Note that this did not affect the 2.4 branch, as pointers were not used.

**Comment by ksshannon** [comment]
Solution leaks memory.  Fixed in 2994bedf40d2ecdc35597c342562750f8b4ffdce
