### ISSUE TITLE
weather.firelab.org is down

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#330]
The link on github to the weather.firelab.org/windninja doesn't work.  Neither does weather.firelab.org

**Comment by nwagenbrenner** [comment]
These are on the OpenStack server that Bryce maintains. It's been down for a couple weeks due to issues that arose while he was upgrading. Hoping it will be back up soon.

**Comment by ksshannon** [comment]
Copy.

**Comment by nwagenbrenner** [comment]
Back up!

**Comment by bnordgren** [comment]
Alex has been steadily making progress on fixing the OpenStack
infrastructure. Some of the VMs are now back up, but I believe there's
still some issues that need to be run down.  Hopefully things stay up now.

Bryce
