### ISSUE TITLE
Update GDAL in travis

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#331]
This is probably why the NOMADS tests are failing. It's probably the same HTTPS issue we had on the mobile server running Ubuntu 14.04.

**Comment by nwagenbrenner** [comment]
@ksshannon instead of installing GDAL with apt-get can we just run build_deps.sh in travis? I'll update the GDAL version in the build script.

**Comment by nwagenbrenner** [comment]
@ksshannon is this still an issue? Or is the the GDAL version in the repo sufficient? Looks like the NOMADS tests are passing now.

**Comment by ksshannon** [comment]
I think it's okay, we can re-open if needed.
