### ISSUE TITLE
Undocumented time_zone

### ISSUE THREAD

**Issue by adriengoeller** [firelab/windninja#335]
Hi, 
I'm using WindNinja as an external module, thanks to the windNinja_cli.
My concern is about the time_zone filling. My data is in UTC, but in the documentation/tutorials/wiki, I only found something like Country/City. 
In wikipedia it is mentionned to use Etc/GMT or utc but it is not working with no error message...
Any idea ?

Thanks
Ad

**Comment by nwagenbrenner** [comment]
@adriengoeller Is this a domain average, point, or weather model initialization? When you say your data is in UTC, which data are you referring to? Can you attach your .cfg file? That might help me understand what you're trying to do.
