### ISSUE TITLE
Add ability to load cloud cover grids for solar simulation

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#337]
Zack Holden has requested that we add the ability to load cloud cover grids as input to the solar-only command line utility.  Issues to determine:
- cloud cover file format (ASCII Grid, GeoTIFF, whatever GDAL can read, ?)
- cloud cover units (% or fraction)

**Comment by nwagenbrenner** [comment]
This is done and tested, right? I'm closing, but re-open if needed.
