### ISSUE TITLE
Ninjafoam: mesh resolution instead of DEM resolution in the output

### ISSUE THREAD

**Issue by VVionnet** [firelab/windninja#339]
In the CLI, by default (ascii_out_resolution=-1),  a NinjaFoam simulation produces outputs (ascii grid for example) at the resolution of the initial DEM instead of the resolution of the mesh. This differs from the gui which works properly and provides the output at the resolution of the mesh. 
Would it be possible to fix this? With Ninjafoam, it is very useful to have the mesh resolution in the output to know at which resolution the model was running since we only specify the mesh count in the config file. 
Thanks!

**Comment by nwagenbrenner** [comment]
Thanks @VVionnet. Yes, the default should be the mesh resolution. I'll look into this, should be a quick fix.

**Comment by nwagenbrenner** [comment]
Fixed in the merge of the foam-mesh branch.
