### ISSUE TITLE
Segfault in point initialization with custom wx station file

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#344]
Necessary files to reproduce are available [here](weather.firelab.org/ninja/windninja). From the user:

I write because I am failing in running an own ‘station’ example (attatched .tif and .csv file). I am running WindNinja under ‘wine’ and I have excecuted all the Tutorial examples without any problem.

You will notice that the attatched files have a ficticious name. I decided to use the ‘missoula_valley’ case as a template to avoid files/folders naming troubles with WindNinja. I put the .csv file inside a folder called ‘WXSTATIONS-2018-06-25-1237-missoula_valley’. Can you run this example? What I am doing wrong?

[station_error.txt](https://github.com/firelab/windninja/files/3393774/station_error.txt)

**Comment by nwagenbrenner** [comment]
The issue may have to do with PROJCS vs GEOGCS. From the user:

I changed the Coord_sys entry to PROJCS and also changed the Lat/YCoord and Lon/XCoord to projected coordinates and the simulation runs without error.

**Comment by ksshannon** [comment]
Repro file link is broken.

**Comment by nwagenbrenner** [comment]
https://weather.firelab.org/ninja/windninja/station_fail.zip

**Comment by nwagenbrenner** [comment]
Fixed the link. The zip file containing the files to reproduce this issue are at:

https://weather.firelab.org/ninja/windninja/station_fail.zip

**Comment by nwagenbrenner** [comment]
No longer have the files to reproduce, but this may have been fixed with #541.
