### ISSUE TITLE
Example .cfg files in latest version (3.5.3) show momentum_solver = true instead of momentum_flag = true

### ISSUE THREAD

**Issue by hjgray10** [firelab/windninja#346]
Just found this while trying out the command line interface

Example .cfg files (cli_momentumSolver_diurnal.cfg) in latest version show: momentum_solver = true.

I looked at the code and found that this should instead be: momentum_flag = true

Sorry if this is the wrong place to report. Or if I did something wrong in general.

Cheers

**Comment by nwagenbrenner** [comment]
@hjgray10 thanks for reporting this. It's been fixed in the master branch. The next release will have the fix.

**Comment by nwagenbrenner** [comment]
Also fixed in the 3.5 branch with dd968d2.

**Comment by hjgray10** [comment]
Thanks!!!
