### ISSUE TITLE
install: supply non-interactive installers

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#347]
Provide both zip and net-aware (using the zip) installers for non-interactive use.  Request by NOAA.

/cc @nwagenbrenner

**Comment by ksshannon** [comment]
@nwagenbrenner next time you build the windows installer, try this:

`$ cpack -G ZIP`

that _may_ do what we need here...

**Comment by fspataro** [comment]
Not sure exactly what you're looking for here... but you're current installer supports "non-interactive" by default:

WindNinja-3.6.0-win64.exe /S /D=d:\temp\wn

/S is for silent - must be uppercase s
/D= optional to override the install path must be last option on cmd-line, no quotes on around th path even if contains spaces

You'll still get the UAC "do you want to allow changes to your computer" dialog if you're not an admin, but running the command prompt as "admin" you get a fully non-interactive install

**Comment by ksshannon** [comment]
I don't have the original use case, but I think it's to avoid administrative privileges, and any UI interaction.
