### ISSUE TITLE
Can it use for other counties？

### ISSUE THREAD

**Issue by ddlddl58** [firelab/windninja#349]
I read your tutorial files, it just support limitied model data, so it can use for other coutries?

Thank u!

**Comment by nwagenbrenner** [comment]
@ddlddl58 Yes, it can be run for any domain in the world. There are global terrain and weather datasets available through the WindNinja interface. The world SRTM and world GMTED terrain data and GFS weather models cover most locations. In addition to the data sources that WindNinja can download for you, you can also supply your own terrain and input wind data to initialize the model.
