### ISSUE TITLE
Compiling ninjaFoam in Ubuntu 18.04?

### ISSUE THREAD

**Issue by SandiaDeDia** [firelab/windninja#350]
Hi, I am trying to compile Windninja (v3.6) on Ubuntu 18.04 with OpenFoam enabled. Windninja compiles and works fine alone but OpenFoam v2.2 crashes on installation. I have installed OpenFoam5 but Windninja is not working with momemtum flag on .  Do you know of any limitations for Ubuntu 18.04 ? should I change to v16.04? Thanks

**Comment by nwagenbrenner** [comment]
@SandiaDeDia WindNinja requires OpenFOAM version 2.2.0. What do you mean the installation crashes? Were you able to install OpenFOAM 2.2.0 following the instructions at the bottom of the page here: https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Linux? I'm not sure our team has tested OpenFOAM 2.2.0 on Ubuntu 18.04, but it should build. We have tested extensively on Ubuntu 16.04, so you could try that if you run into issues on 18.04. Don't forget that once you have installed OpenFOAM, you will need to build our custom libraries and applications:

    mkdir -p $FOAM_RUN/../applications
    cp -r ~/src/wind/windninja/src/ninjafoam/* $FOAM_RUN/../applications
    cd $FOAM_RUN/../applications
    wmake libso
    cd utility/applyInit
    wmake

**Comment by SandiaDeDia** [comment]
Hi Natalie,I was finally able to compile OpenFoam2.2.0 but now I am having some problems with windninja. I will investigate a bit more first, just wanted to thank you for your quick response. Cheers.

**Comment by nwagenbrenner** [comment]
Closing, re-open if needed.

**Comment by SandiaDeDia** [comment]
Hi Natalie, sorry for the late feedback. Yes, we were finally able to compile in Ubuntu 18.04. Thank you for the support.
