### ISSUE TITLE
number time step does not correspond with step in time during the wind processing

### ISSUE THREAD

**Issue by adriengoeller** [firelab/windninja#352]
Hi, 

First, I would thanks all the contributors of this project. WindNinja is a very promising code for interpolating wind, perhaps the most easy to use !
I'm using the windNinja_cli.exe to drive windninja without the front. In order to have a minimal command, I use the pi.cfg to define all the parameter.
My start date : 31/12/2018 - 01h00
My end date : 31/12/2018 - 05h00
The issue is : 
 - When i put number_time_steps = 3 
I get the results on the time steps 1h00 , 2h20, 5h00
 - When i put number_time_steps = 4 
I get the results on the time steps 1h00 , 2h00, 3h00 , 5h00
 - When i put number_time_steps = 5 
I get the results on the time steps 1h00 , 1h48 , 2h36, 3h24, 5h00

==> No way to have 1h00 , 2h00, 3h00 , 4h00 , 5h00, which corresponds to the timesteps provided in the meteo csv stations files.

Another question : when the time steps does not correspond with meteo provided in csv files, what is the meteo inputs (would the meteo be interpolated in time ?? That kind of process could generate bias on results...when it is not wanted)

Thanks

**Comment by ksshannon** [comment]
Can you give us a little more context on your runs?  Can you attach the config file and any other files you used to do the run(s)?

**Comment by adriengoeller** [comment]
Yes sure.
Here are the stations files and the .cfg

**Comment by adriengoeller** [comment]
Yes for sure.
Here is my cfg file :
num_threads              = 8
    elevation_file           = somepath\...\BDALTI_4.tif
initialization_method    = pointInitialization
    time_zone		 = 	Europe/Paris
    match_points             = false
    wx_station_filename      = somepath\...\TEMPSTATION-MDT\stations_8.csv
write_wx_station_kml     = false
start_year		 = 2018
start_month   = 12
start_day		 = 31
start_hour		 = 01
start_minute		 = 00
end_year		 = 2018
end_month		 = 12
end_day			 = 31
end_hour		 = 05
end_minute		 = 00
number_time_steps  	 = 4
output_wind_height       = 10.0
    units_output_wind_height = m
    vegetation               = grass
mesh_resolution          = 25
units_mesh_resolution    = m
    write_goog_output        = false
write_shapefile_output   = false
    write_ascii_output       = true
    write_farsite_atm = false

**Comment by adriengoeller** [comment]
Yes for sure.
Here are the cfg file (renamed in .txt for uploading) and the station files used.
[cfg.txt](https://github.com/firelab/windninja/files/4092019/cfg.txt)
[TEMPSTATION-MDT.zip](https://github.com/firelab/windninja/files/4092004/TEMPSTATION-MDT.zip)

**Comment by nwagenbrenner** [comment]
Right now the only option is to use interpolation between timesteps to simulate the requested number of timesteps. It was set up this way because often more than one station is used for initialization and the stations often report on different timesteps. We needed a way to get consistent timesteps across the stations. It would be ideal to also have the option to initialize from a specified list of times (without interpolation) if only a single station was being used or for multiple stations reporting on the same timesteps.

**Comment by adriengoeller** [comment]
Ok @nwagenbrenner ! Thinks for your answer to my interpolation question. It seems normal to interpolate with asynchronous data on each source.
But for me it does not explain the behavior described below.
It is impossible to have the output on five time steps at 1h, 2h, 3h, 4h and 5h. It seems that windninja calculates the time step `dt = ( start_date - ( end_date ) ) / number_time_steps` and then apply it to generate the time vector for interpolation but only number_time_steps-2 times.
In my case : 
> My start date : 31/12/2018 - 01h00
> My end date : 31/12/2018 - 05h00
> number_time_steps = 4
`dt = (5h - 1h) / 4 = 1h`
`time vector = [ 1h , 1h+dt , 1h+2dt , 5h] = [ 1h , 2h , 3h , 5h]` missing the 4h timestep.

So if I want the time vector, I have to ask between 1h and 7h : I get 1h, 2h, 3h, 4h, 5h, and 7h. Another question here : is windninja extrapolate data to compute at 7h ? Are the 1h, 2h, 3h, 4h, 5h corresponding to the time in the meteo files ?

Thanks again

**Comment by nwagenbrenner** [comment]
@adriengoeller thanks for reporting this issue and providing all of the details to reproduce it. There was an error in the way the time list was being generated from the requested start/stop times and number of timesteps in the cfg file. I made a change in the master branch that should fix the issue for you. Let us know if it works for you.
