### ISSUE TITLE
[windninja_cli] : Impossible to configure UTC time on .cfg file

### ISSUE THREAD

**Issue by adriengoeller** [firelab/windninja#353]
When parameter time_zone = UTC or GMT, windninja does not launch.
I bypass the issue by taking a time_zone = Conitnent/City but it should be great to work all in UTC.

**Comment by ksshannon** [comment]
UTC and GMT have been added to the time zone file.  You can replace your local version with:

https://raw.githubusercontent.com/firelab/windninja/master/data/date_time_zonespec.csv

And 'GMT' and 'UTC' should be available.
