### ISSUE TITLE
[windninja_cli] : false (?) error 407 given by windninja_cli

### ISSUE THREAD

**Issue by adriengoeller** [firelab/windninja#354]
Hi,

Even if my .cfg file seems good and windninja computes the output normally, it display on screen : 
`ERROR 1: HTTP error code : 407`
`Run 0: Reading elevation file...`
`Run 1: Reading elevation file...`
`Run 0: Simulation time is 2018-Dec-31 01:00:00 CET`
`Run 0: Run number 0 started with 1 threads.`
`Run 0: Generating mesh...`

When my .cfg has some incorrect parameter, I get only : `ERROR 1: HTTP error code : 407`

More generally, it would be great to have some information on the error (which parameter is not correct for example).

**Comment by ksshannon** [comment]
> Hi,
> 
> Even if my .cfg file seems good and windninja computes the output normally, it display on screen :
> `ERROR 1: HTTP error code : 407`
> `Run 0: Reading elevation file...`
> `Run 1: Reading elevation file...`
> `Run 0: Simulation time is 2018-Dec-31 01:00:00 CET`
> `Run 0: Run number 0 started with 1 threads.`
> `Run 0: Generating mesh...`
> 
> When my .cfg has some incorrect parameter, I get only : `ERROR 1: HTTP error code : 407`

That is a non-fatal error displayed when WindNinja cannot download certain files on startup.  It is no longer shown in master.  It does not indicate an error in the config file.

> 
> More generally, it would be great to have some information on the error (which parameter is not correct for example).

As I mentioned the error above is separate from the config file options, what message do you see with an incorrect parameter?

**Comment by adriengoeller** [comment]
@ksshannon 
Thanks for your fast support !
My point is that if some parameter in the cfg file is not correct (example: UTC for the time zone), you have no information that the incorrect parameter is the time zone. 
You are trying to know first if the error is in the cfg file or in the station file, and then which parameter is not accepted by windNinja.
&rightarrow; It would be great to have some message/log somewhere (in a file perhaps ?) which could explain why windNinja is not running other than `ERROR 1: HTTP error code : 407`

**Comment by ksshannon** [comment]
@adriengoeller, The HTTP error isn't really an error.  WindNinja will run if that fails, that is why it doesn't stop immediately.  When I substitute UTC (before the change that made UTC/GMT available) as the timezone in `data/cli_domainAverage_diurnal.cfg`, I get the following error:

```
$ WINDNINJA_DATA=../data ./src/cli/WindNinja_cli test.cfg 
Run 0: Reading elevation file...
Exception caught: The time is not set correctly.
Exception caught: The time is not set correctly.
```

Which isn't as good as it should be, but it does reference time.  Your output is suggesting something else is going wrong and we are looking at something that may not be the actual issue.

Can you post all of the files necessary to reproduce your error?

**Comment by ksshannon** [comment]
Closing due to lack of feedback, re-open if necessary.
