### ISSUE TITLE
Generate metadata file with information about the simulation

### ISSUE THREAD

**Issue by jesusrl69** [firelab/windninja#361]
Hi,
I use WindNinja output files as a input for a fire forest simulation software. But i don't have information about the output height and the output speed units. I think generating a metadata file with this information is quite easy and very useful.

Thanks, Jesús

**Comment by nwagenbrenner** [comment]
Are you running WindNinja via the graphical user interface? If you're using the graphical user interface, the output height and speed units are displayed for you in the "Output" tab. If you click on "Output" above "Google Earth" you'll see what the output height and output speed units are defaulted to. You can also change these default settings here. Let us know if this answers your question.

**Comment by jesusrl69** [comment]
I will try to clarify the problem, since it seems that I have not explained myself well.
I'am a software developer. I'am writing a fire forest simulation software. One of the inputs to my software is a wind field generated by WindNinja. I need to know the height at which the output was generated, the unit at which the wind speed is and the SRS of the map. The SRS of the map is easy to obtain by reading the prj file. But the height and the unit I must ask the user because it is not recorded anywhere (I use the shapefile format output). 
My proposal is to generate a metadata file where at least the height at which the map was generated and the wind speed measurement unit are saved, in the same way that the SRS is saved in the PRJ file. The format of that metadata file doesn't matter to me, although I would personally prefer a JSON.

**Comment by nwagenbrenner** [comment]
We have plans to eventually implement a case file for WindNinja which could include this metadata and other settings used to set up the run (#7). In the meantime, you could ask the users to provide this metatdata for you since the user will know what settings they used to initialize the run. Or you could ask your users to use a standard output height and output speed units.

**Comment by jesusrl69** [comment]
Thanks, Natalie.
That is just what I am doing now, asking the user for this metadata. But being a software used by research groups, they pass files to each other and it is easy for them to be wrong in providing this metadata. Being in a small standard text file, we eliminate all possibility of error. As I mentioned, it is exactly the same problem as with the SRS, until the PRJ file was implemented.
I will wait for the implementation of the case file.

**Comment by jesusrl69** [comment]
I have carefully read the case file  [(#7)](https://github.com/firelab/windninja/issues/7) request, and note that it varies substantially in the purpose and functionality of this request.
The case file would be optional and would require user action. My metadata file proposal is to make it automaticaly (in the same way that the PRJ file is generated), and only for output information, not for reuse as input in WindNinja.

**Comment by ksshannon** [comment]
@jesusrl69 it is unclear what you are actually proposing.  Assuming we write out a metadata file, it suffers from the same problems any other passed around files do.  How exactly would this work?  Is there one metadata file for each output file or file set?

**Comment by jesusrl69** [comment]
I propose to create a metadata file for each output file (SHP, KMZ, VTK, ASC, ...), exactly as is done with PRJ files. The only difference is that the PRJ files are copied from the input DEM file, and this new file would have to be generated from WindNinja with just some data: height, height units and speed units.
The content of this file could be as simple as (assuming JSON format):
`{
    "Height": 6,
    "Height units": "ft",
    "Speed units": "mph"
}`
In this way (assuming output to shapefile), in addition to the SHP, DBF, SHX and PRJ files, a fifth file with the proposed content and the same name, with different extension, would be generated. Any program that makes use of this shapefile could read this file and thus not have to ask the user at what height it was generated or the units of the wind speed.
The exact format of the file can be JSON, as I suggest, or any other text format you choose. The file extension can be anyone that does not collide with existing extensions. It could be, for example, something like .WNM (WindNinja Metafile).

**Comment by ksshannon** [comment]
Can you give us some context on how you are using WindNinja?  It's rare that people use the output when they have not created it.  I'm not even sure how you'd vet it was created by WindNinja in the first place.  Are you not running WindNinja, just consuming the output from unknown sources?

**Comment by fspataro** [comment]
@ksshannon We had a couple issues with the WNServer processor that would have been much easier if an 'output' file was generated.  I thought I had logged them somewhere but I'm not finding them with a quick search.  What I remember:

The process has to monitor the STD-OUT so it can pick up the values and errors rather than read something at the end.  Sometimes the STD-OUT message output changed and broke our parser method.   Anytime the cli parameters let the WindNinja 'choose' a value, it was an issue b/c we didn't know what value was used.  Figuring out which output was generated was guess work off file system 'list' commands rather than a known set of values. 

A lot of this revolved around TimeZone and output naming.  

We solved a bunch of this by using the cfg for input and generating our own 'result file' to keep track of these things and send along to the next parts of the pipeline but i would have been much easier from the start if the cli had generated it for us.

**Comment by jesusrl69** [comment]
@ksshannon As I described earlier, I am not an end user of windninja but a software developer who needs the WindNinja generated windmap as input to my forest fire simulation program. This software is used by research groups and in university teaching. On many occasions, students are provided with the generated wind map, and it is necessary to explain to them at what height it was generated and in what units the wind speed is, so that they can enter it in my software. This wind map may have generated some previous academic year and the height and speed unit data must be documented manually (for example, in the file name). There are always students who make mistakes when entering the data and the result is obviously not as expected. If this data were in a metadata file, no error would be expected.

It is the same problem that happened years ago, when GIS generated shapefiles without PRJ files. You had to remember where SRS these shapefiles were, and it was easy to be wrong. When the PRJ files were generated, these problems disappeared.

**Comment by ksshannon** [comment]
> @ksshannon We had a couple issues with the WNServer processor that would have been much easier if an 'output' file was generated. I thought I had logged them somewhere but I'm not finding them with a quick search. What I remember:
> 
> The process has to monitor the STD-OUT so it can pick up the values and errors rather than read something at the end. Sometimes the STD-OUT message output changed and broke our parser method. Anytime the cli parameters let the WindNinja 'choose' a value, it was an issue b/c we didn't know what value was used. Figuring out which output was generated was guess work off file system 'list' commands rather than a known set of values.
> 
> A lot of this revolved around TimeZone and output naming.
> 
> We solved a bunch of this by using the cfg for input and generating our own 'result file' to keep track of these things and send along to the next parts of the pipeline but i would have been much easier from the start if the cli had generated it for us.

Okay, I see.  There is ambiguity in some values, as they may not be passed in or known at the time.  The output convention is bad, I know, and I think a Save-As (file or directory, not sure) would handle most of that.  

It would not handle the self-population of the time zone stuff though.  Thanks for the feedback.

**Comment by ksshannon** [comment]
> @ksshannon As I described earlier, I am not an end user of windninja but a software developer who needs the WindNinja generated windmap as input to my forest fire simulation program. This software is used by research groups and in university teaching. On many occasions, students are provided with the generated wind map, and it is necessary to explain to them at what height it was generated and in what units the wind speed is, so that they can enter it in my software. This wind map may have generated some previous academic year and the height and speed unit data must be documented manually (for example, in the file name). There are always students who make mistakes when entering the data and the result is obviously not as expected. If this data were in a metadata file, no error would be expected.
> 
> It is the same problem that happened years ago, when GIS generated shapefiles without PRJ files. You had to remember where SRS these shapefiles were, and it was easy to be wrong. When the PRJ files were generated, these problems disappeared.

@jesusrl69 I think a case file is the appropriate solution here.  @fspataro brought up another piece of metadata that has no record of being set, but why not others such as input method, initialization parameters, etc.  There is little provenance to a lot of the input data, I don't see why this would be limited to just the two values you are seeking.  We probably need to think on the best route forward here.

**Comment by jesusrl69** [comment]
> > @ksshannon As I described earlier, I am not an end user of windninja but a software developer who needs the WindNinja generated windmap as input to my forest fire simulation program. This software is used by research groups and in university teaching. On many occasions, students are provided with the generated wind map, and it is necessary to explain to them at what height it was generated and in what units the wind speed is, so that they can enter it in my software. This wind map may have generated some previous academic year and the height and speed unit data must be documented manually (for example, in the file name). There are always students who make mistakes when entering the data and the result is obviously not as expected. If this data were in a metadata file, no error would be expected.
> > It is the same problem that happened years ago, when GIS generated shapefiles without PRJ files. You had to remember where SRS these shapefiles were, and it was easy to be wrong. When the PRJ files were generated, these problems disappeared.
> 
> @jesusrl69 I think a case file is the appropriate solution here. @fspataro brought up another piece of metadata that has no record of being set, but why not others such as input method, initialization parameters, etc. There is little provenance to a lot of the input data, I don't see why this would be limited to just the two values you are seeking. We probably need to think on the best route forward here.

@ksshannon For my part, there would be no problem in the input metadata being generated (not just the output metadata). This is useful information in some circumstances and I see no reason why they should not be included. It would be enough if the input and output data were clearly differentiated.

As the file case in (#7 ) is stated, I am concerned that the generation of this file is optional, and that it is immutable. I think it should always be generated, and whoever needs it uses it. The purpose of the file case and the proposed metadata file is different, but it can probably be done in a way that satisfies the requirements of both.

**Comment by nwagenbrenner** [comment]
Initial work for a casefile can be found in the casefile branch. This will be merged into master soon. This is being tracked in #7 so closing this issue.
