### ISSUE TITLE
Radius of Influence entry in cfg file

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#367]
Thank you all for this beautiful product.  As I delve into it more and more I feel like some additional functionality would allow users to be much more productive. One of these additions would be to add an entry for the cfg file for the radius of influence when initializing with pointInitialization. Currently, if you fetch station data this field is populated with -1.  With this value (although it means infinite) station values do not propagate beyond their periphery much. You can almost identify station locations by simply looking at the wind field. See attached image for example. I could make this more meaningful by applying a new radius of influence depending on the density of the stations but this means I have to rerun the simulation.  It would be really nice to have this option available so that:
1) we can specify our own radius of influence
2) have options on this based  on the fetched station density. 
many thanks
nc
![roiInf](https://user-images.githubusercontent.com/53827558/81441307-8ba47700-913f-11ea-8b22-0f332e8caabe.PNG)

**Comment by nwagenbrenner** [comment]
Thanks for the question. We've considered other interpolation methods, but it's tricky to come up with a method that will work well for all cases. We'll continue to think about this and see if we can't come up with a better scheme. 

For now, one thing you could try is setting the environment variable `NINJA_POINT_INV_DIST_WEIGHT` to something larger than one. This option sets the inverse distance weighting used, where 1 is the default and corresponds to inverse distance, 2 would be inverse distance squared, etc. Increasing this value should allow stations to have more influence over larger distances.

**Comment by ncubukcu** [comment]
Thanks nwagenbrenner.  It is indeed better if I take your advice and increase the env variable NINJA_POINT_INV_DIST_WEIGHT. I have to say this is a bit confusing to me since "inverse distance" weighting should diminish weight faster as you increase power (weight= 1/distance**power) but I guess you use a convention that I am not familiar with. 

Also since inverse distance is used what is the role of "radius of influence" exactly?  For example, let us assume that "radius of influence" column in station csv file is changed to say 20km. In this case inverse distance weighting is limited to 20km and any distance beyond that gets zero weight?

thanks

**Comment by nwagenbrenner** [comment]
Yeah, the reason the smoothing improves is because you are using inverse distance for all of the stations. The stations that are farther away have even less weight at a given point than the nearer stations, which improves the smoothing.

Yes, your interpretation of the radius of influence is correct. At least one station must have an infinite radius of influence to ensure all points in the grid have an initial wind, but other stations could use some other radius of influence.

We do plan to look into other smoothing options in the future. I'll create a ticket on here to track the issue.
