### ISSUE TITLE
Minor naming inconsistencies with shapefile outputs

### ISSUE THREAD

**Issue by fspataro** [firelab/windninja#37]
This is definitely somewhat trivial but while creating server-side and client UI for the output, consistency in the naming pattern makes coding a little easier and less error prone to all the different flavors.  I haven't checked all the models or other output types but here's what we see:

FIRST: Ninja outputs vs Wx outputs

Ninja output files are named in the pattern:
{surface file}_{date}_{time}_{grid?}

Wx model output files are named in the pattern:
{model name}-{date}_{time}

Finding date/time in both requires two different patterns.  The model names have underscores in them so that presents a problem for using the underscore as the consistent separator...  maybe dot?  not sure how the other platforms like dots inside the files names.  

SECOND: Wx model name prefixes
NOMADS and UCAR models write their wx shapefile outputs differently as well:
NOMADS: hrrr_conus-02-17-2015_2000
UCAR: UCAR-NAM-CONUS-12-KM-02-17-2015_1700

In this case it would be nice to regurgitate the entire model name consistently.  

Nit-picky stuff but these are some of the things we bump into creating workflows downstream of the output.

**Comment by ksshannon** [comment]
Fixed in 82be12eccf65bf089ca321872fc5d93c6097b6db
