### ISSUE TITLE
Can't install Wind Ninja in Linux

### ISSUE THREAD

**Issue by aklibenali** [firelab/windninja#374]
Hi

I get this error:

git clone https://github.com/firelab/windninja.git 
Initialized empty Git repository in /root/windninja/.git/
error:  while accessing https://github.com/firelab/windninja.git/info/refs

fatal: HTTP request failed

Any ideas? Thanks

**Comment by nwagenbrenner** [comment]
I think this must have been either a temporary issue with the GitHub servers or some issue in your git configuration? I'm able to clone the repo without any issues.

**Comment by ksshannon** [comment]
github has been having issues today, re-open if anything else comes up.
