### ISSUE TITLE
Fake user created stations

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#376]
Hi
Here is an interesting experiment. Since there are only limited nwp forecast/analysis options, I decided to run hourly Ecmwf Era5 surface wind as if the data belongs to stations. Figure below shows fake stations in red. Each of these red spot is a faked station and it has a station file as attached. 

WindNija cli runs fine and computes the first hour but it cannot move on and runs the second time step. It stops with this error message:

Run 0: Run number 0 done!
Exception caught: std::exception

My research on this error points to model data having gaps in the computation domain. I do have some ocean points here I eliminate but that should not be an issue. Any idea what is happening here? Thanks

The configuration file is as follows:
num_threads=2
elevation_file=Sonoma.lcp
initialization_method=pointInitialization
wx_station_filename      =SonomaStations.csv
time_zone=GMT
match_points=false
write_wx_station_kml=true
#write_wx_station_csv=true
start_year=2017
start_month=10
start_day=9
start_hour=6
start_minute=0
end_year=2017
end_month=10
end_day=9
end_hour=7
end_minute=0
number_time_steps=2
station_buffer=10
station_buffer_units=km
output_wind_height=20
units_output_wind_height=ft
output_path=Output
mesh_resolution=250.0
units_mesh_resolution=m
write_goog_output=true
goog_out_resolution = 1000
units_goog_out_resolution=m
write_shapefile_output=true
write_ascii_output=false
write_farsite_atm=true

A station entry:
Station_Name,"Coord_Sys(PROJCS,GEOGCS)","Datum(WGS84,NAD83,NAD27)",Lat/YCoord,Lon/XCoord,Height,"Height_Units(meters,feet)",Speed,"Speed_Units(mph,kph,mps,kts)",Direction(degrees),Temperature,"Temperature_Units(F,C)
",Cloud_Cover(%),Radius_of_Influence,"Radius_of_Influence_Units(miles,feet,meters,km)",date_time
Id12X5,GEOGCS,WGS84,38.59999999999994,-122.40000000000015,10,meters,5.490193843841553,mps,16.127632039373204,75,F,20,-1,km,2017-10-09 06:00:00
Id12X5,GEOGCS,WGS84,38.59999999999994,-122.40000000000015,10,meters,5.742762565612793,mps,18.67458107671506,75,F,20,-1,km,2017-10-09 07:00:00
Id12X5,GEOGCS,WGS84,38.59999999999994,-122.40000000000015,10,meters,5.9076995849609375,mps,20.488982015260287,75,F,20,-1,km,2017-10-09 08:00:00
Id12X5,GEOGCS,WGS84,38.59999999999994,-122.40000000000015,10,meters,5.845408916473389,mps,21.126889528306066,75,F,20,-1,km,2017-10-09 09:00:00

![EcmwfGrids](https://user-images.githubusercontent.com/53827558/84073180-4ffb0800-a99e-11ea-9c90-03dfe36f43a2.PNG)

**Comment by ksshannon** [comment]
What does the ECMWF data look like?  It's possible with a few tweaks to get it to run with the existing infrastructure.  As for the exception, it's difficult to tell with out replicating it.  The ocean values shouldn't matter as long as they aren't no data values.

**Comment by ncubukcu** [comment]
Hi Kyle
I have a test test [here ](https://drive.google.com/drive/folders/1jewgB9hcLSv-uiE8-c8rBPfD1lf4CQsp?usp=sharing) if you want to try. 

https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview describes the era5 land data. As you see above I make a slightly extended boundary around the county I'm running windninja and only keep grid points within the border.  I would be lovely to have this set available for windninja. As far as I know this set is probably the best 10m wind analysis out there. 

Thanks

**Comment by nwagenbrenner** [comment]
The .prj file for the .lcp is missing in the test case. Can you add this and we'll take a look?

**Comment by ncubukcu** [comment]
They are included there separate from the zip file actually. Please double check if not I will bundle them all together. Thanks

**Comment by ncubukcu** [comment]
This may very well be memory issue. I see some evidence of it  when I change number of CPUs.  Speaking of this. Is there a cli option to let us know about the memory needed for a run? 
Thanks

**Comment by ksshannon** [comment]
@ncubukcu is it possible to get the original ECMWF data?  I'm curious about how it's organized.

**Comment by nwagenbrenner** [comment]
I've got the files necessary to reproduce and I'm looking into it. You probably shouldn't use the pointInitialization for gridded input data though. Point initialization isn't really set up to handle gridded data properly. You could try the griddedInitialization option described in #359 and #269. Others have used this successfully for initialization with weather model output that WindNinja can't read in directly.

**Comment by nwagenbrenner** [comment]
The time is set incorrectly. It's in the csv files as 

`2020-06-09 00:25:00`

but needs to be in this format:

`2020-06-09T00:25:00Z`

I'll add a check on the datetime format.

**Comment by ncubukcu** [comment]
Darn. Thanks you very much. Also thanks for the griddedInitialization tip. I did not know it was there.  You asked about era5 data format which you can get in https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview. Once you decide what dates and what variables you want, it is then up to you to choose the output format. It could be grib or netcdf or even a png file.  Thank you very much..

**Comment by ncubukcu** [comment]
> The time is set incorrectly. It's in the csv files as
> 
> `2020-06-09 00:25:00`
> 
> but needs to be in this format:
> 
> `2020-06-09T00:25:00Z`
> 
> I'll add a check on the datetime format.

Just to note here that WindNinja version: 3.6.0 does not like 'Z' at the end. It only  works without it. Thanks
