### ISSUE TITLE
CentOS installation

### ISSUE THREAD

**Issue by chjones2** [firelab/windninja#377]
hello,

I am trying to compile windninja on a CentOs linux cluster. 
I did installed the boost package as:
sudo yum install boost

but cmake is giving these configuration errors:

VERSION: 3.6.0
PKG VERSION: WindNinja-3.6.0
Could NOT find Boost
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:89 (find_package)

any ideas how to fix this?

thank you very much.

Charles.

**Comment by ksshannon** [comment]
Try `sudo yum install boost-devel`

**Comment by chjones2** [comment]
it worked - thanks!
