### ISSUE TITLE
Race condition when running multiple WN instances with same outputdir

### ISSUE THREAD

**Issue by Chrismarsh** [firelab/windninja#382]
To aid parallelism (partially because of the OMP issue #355), I am running multiple WindNinja instances over different parts of my domain. Each instance is told to write a unique output to the same target folder.

However because of this check
https://github.com/firelab/windninja/blob/3.6/src/ninja/ninja.cpp#L4513

there is a race condition when multiple WN instances are launched almost simultaneously (I'm seeing this with concurrent futures in python) that this detection fails due to all the WN instances trying to create and delete the same test folder.

**Comment by ksshannon** [comment]
@Chrismarsh can you check master at the latest commit?

**Comment by ksshannon** [comment]
@Chrismarsh nevermind, I mis-read some docs.  Fix coming...

**Comment by ksshannon** [comment]
@Chrismarsh please try on master.

**Comment by Chrismarsh** [comment]
Looks good on my end, thanks!

**Comment by ksshannon** [comment]
It's not 100% fool-proof without knowing the semantics of the functions I used.  Please re-open if you run into any more issues.
