### ISSUE TITLE
wrfout.nc cause lat/long exception in ninja::set_position()

### ISSUE THREAD

**Issue by Chrismarsh** [firelab/windninja#383]
When loading a wrfout.nc I get the error 

`Exception caught: Latitude greater than 90 degrees or less than -90 degrees in ninja::set_position().`

I've traced the code and it seems to me that the lat and long values are swapped. 

From gdb here
https://github.com/firelab/windninja/blob/95f392d93d8db5e59e6c6160c176151ef99227bb/src/ninja/ninja.cpp#L4190

```
lon = {double} 50.900377879743679
lat = {double} -115.23122284901007
```

I tried swapping lat/long just to see and it doesn't work

```
Run 0: Reading elevation file...
Run 0: Simulation time is 2017-Sep-01 00:00:00 MDT
Run 0: Generating mesh...
Run 0: Initializing flow...
Exception caught: Invalid cell reference in AsciiGrid<T>::get_cellIndex().
Exception caught: Invalid cell reference in AsciiGrid<T>::get_cellIndex().

```

This occurs with a wrfout.nc I've created myself. It also happens with a wrfout Natalie provided me, however I'm not totally sure of the DEM to be using with it. It does not happen with the `20170603T1800.nc` and `big_butte_small.tif` files in the example data dir.

**System details:**

```
$ uname -a
Darwin lappy.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**CMake**
I have added these lines to the top of the CMakeLIsts.txt otherwise I have a problem with the code not detecting a C++11 compiler
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

Invocation
```
cmake -DCMAKE_BUILD_TYPE=Debug -DNINJA_QTGUI=FALSE -DNINJAFOAM=FALSE -DNINJA_SCM_REVISION=1 -DOPENMP_SUPPORT=FALSE -G "CodeBlocks - Unix Makefiles" ~/windninja
```

**Comment by Chrismarsh** [comment]
I wonder if this could it be related to the GDAL3.0 change surrounding the transform function?
https://gdal.org/tutorials/osr_api_tut.html?highlight=transform#crs-and-axis-order
https://github.com/OSGeo/gdal/issues/1546

**Comment by ksshannon** [comment]
Closing this, see #384 for a more general purpose issue.
