### ISSUE TITLE
Update coordinate transformations to proj 6.x+

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#384]
See #383 for an example.  Any WGS84 transformations need to be inspected.  Linking against GDAL 3.x or higher will fail.

**Comment by nwagenbrenner** [comment]
There is another instance of this issue in `GDALPointFromLatLon` which affects wx model and point initializations.

**Comment by nwagenbrenner** [comment]
I think 36a8c70 got the remaining instances.
