### ISSUE TITLE
Multi threading issue?

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#385]
Hi
I run multiple ninja runs concurrently using momentum solver in Linux env and I see some peculiar error messages popping up randomly. I feel like multiple runs somehow share common output temp files or log files. It is hard to pinpoint this since I have no control on output file names or log file names. With openfoam, we have so many log files to manage. One error is this:

Run 0: Error during simpleFoam(). Can't coarsen mesh for existing case directory. Try again without using an existing case.
Return of false from simulate_wind()Run 0: Error during simpleFoam(). 

I am pretty sure I am not running an existing case. What is "existing case directory" in this message? 

Another error  I get is about the file permissions on the output directory. It says it does not have permission to write there so it will write to default location. I may have two ninja runs writing into a same output directory but they are supposed to create different output files.  Here is tthe error:
Run 0: Cannot write to path csim/W121N033/OutputMom-Dir-0. Do you have write permission on this directory? Writing outputs to default location...
Run 0: Reading elevation file...

Not sure how to duplicate this or provide a sample case to show you guys. As I said this looks pretty random. 
Thanks

**Comment by ksshannon** [comment]
What version are you running?  There are a couple of fixes on master recently that may fix this, if you can use the latest commit on the master branch, please try it and report back if it still is an issue.  The commits in question:

22ab37c580d97e27381162c99ab1febd1cdba404
8c42c574976785e3a21fde52535dc609f6f37d72

**Comment by ncubukcu** [comment]
> What version are you running? There are a couple of fixes on master recently that may fix this, if you can use the latest commit on the master branch, please try it and report back if it still is an issue. The commits in question:
> 
> [22ab37c](https://github.com/firelab/windninja/commit/22ab37c580d97e27381162c99ab1febd1cdba404)
> [8c42c57](https://github.com/firelab/windninja/commit/8c42c574976785e3a21fde52535dc609f6f37d72)

**Comment by ncubukcu** [comment]
Thanks Kyle.

WindNinja version: 3.6.0
SCM version: 0dbb3f3519feb84d930fc06db43170f80bbd2ba7
Release date: 2020/07/07
OpenMP enabled (40)

I will run the update and  report back..
regards
