### ISSUE TITLE
WRF Input: COSMO-d2

### ISSUE THREAD

**Issue by RafaelAbel** [firelab/windninja#393]
Dear windNinja-Team,
first of all thanks for developing and maintaining such a great tool!

I have been plaing around with windNinja and wanted to use the high-res german WRF model (which you can find here:
https://opendata.dwd.de/weather/nwp/cosmo-d2/grib/00/u_10m/ )

This tutorial (https://weather.firelab.org/windninja/tutorials/WindNinja_tutorial4.pdf) says, that it is possible to use other models than the specified and downloadable models. However, I could not get it running. I combined the U and V component in one file, but still the GUI cannot find it.

Any help is highly appreciated!

**Comment by nwagenbrenner** [comment]
@RafaelAbel Sorry for the slow reply. What format is your wrf output in? WindNinja can handle WRF-ARW output in the standard NetCDF format (often referred to as "wrfout" files). If you  have this output, WindNinja should be able to read it. If you don't have access to the original NetCDF output there is another option (you could do a griddedInitialization), but using the NetCDF output directly would be the easiest/best option.

**Comment by nwagenbrenner** [comment]
Please re-open if there are still questions here.
