### ISSUE TITLE
lcp landscape file download fails on RH 7 Linux build

### ISSUE THREAD

**Issue by tcarternws** [firelab/windninja#404]
Attempting to download a .lcp landscape file I get this error:

Downloading elevation file...
ERROR 6: GEOS support not enabled.
ERROR 6: GEOS support not enabled.
ERROR 6: GEOS support not enabled.
ERROR 1: Failed to locate product.
Failed to download elevation data

Can you please point the direction to enable GEOS support on Linux RH Enterprise 7.  I don't see it as a ccmake configuration.

**Comment by nwagenbrenner** [comment]
It sounds like GDAL was built without GEOS support. You'll need to be sure GEOS is installed. On Ubuntu the package is `libgeos-dev`. You'll need to find and install the appropriate package for your system. It looks like it might be `geos-devel`.  Once you have GEOS installed, you'll need to re-build GDAL to enable GEOS support. You can double check that GDAL finds your GEOS install by looking at the output from configure.

**Comment by tcarternws** [comment]
Installed GEOS and recompiled GDAL. Now I get a URL error. Any advice?

Downloading elevation file...
ERROR 1: HTTP error code : 404
ERROR 1: Failed to generate valid URL for LCP download.
Failed to download elevation data

**Comment by nwagenbrenner** [comment]
LANDFIRE has been down for several days. Hopefully it's back up next week.
