### ISSUE TITLE
Momentum data visualization from Windows

### ISSUE THREAD

**Issue by alcliberal** [firelab/windninja#413]
I try to follow the " https://cfd.direct/openfoam/user-guide/v6-paraview/ " but I couldn't find the paraFoam on WindNinja for windows.

**Comment by nwagenbrenner** [comment]
@alcliberal We don't distribute ParaView or the full OpenFOAM installation with WindNinja. We only distribute the required libraries and applications needed to run the flow simulation. If you want to view the OpenFOAM output, you'll need to install OpenFOAM and ParaView. The easiest way to do this is on Linux, although certain versions of OpenFOAM can be compiled on Windows.

**Comment by alcliberal** [comment]
Thank you for anwsering quickly. I try to run the output folder, "NINJAFOAM_missoula_valley_11128_2" of "cli_momentumSolver_diurnal.cfg" but there is neither .foam nor .vtk files between the outputs. I run the windows WindNinja_cli.exe and I don't know if the solution folder is incomplet or I don't know how to open the .raw and .vrt files on ParaView.
![image](https://user-images.githubusercontent.com/63002869/120897694-c2d9a600-c627-11eb-90a5-3f4896904822.png)

**Comment by nwagenbrenner** [comment]
The files that are viewed in paraview are in constant/polymesh (the mesh) and the last timestep, in your case 2052/ (the data). You need to run paraFoam which does some manipulation on the case file to allow ParaView to open the files.
