### ISSUE TITLE
Conservation of Momentum by Using CLI

### ISSUE THREAD

**Issue by Porkking** [firelab/windninja#414]
I have a question about the log from CLI when I using conservation of momentum. It seems like I must decide the output height. And I just find that the solver shows:
Run 0: (solver) 32% complete...
Run 0: (solver) 32% complete...
Run 0: (solver) 32% complete...
Run 0: (solver) 33% complete...
Run 0: Sampling at requested output height...
Run 0: File writing time was 0.163202 seconds.
Why does it start to write the result when the solver does not finish?

Also, what is the meaning of number of iterations? What number of iterations is recommended?

**Comment by nwagenbrenner** [comment]
The number of iterations is the number of times the solver is run. It takes many iterations for the solver to reach a steady-state solution. We estimate the number of iterations that are necessary at runtime based on the resolution of the domain. It's possible that the solver is reaching a steady-state before we reach the estimated number of iterations. This happens sometimes and could be why the solver is finishing when we think it is only 33% complete based on the estimated number of iterations. Does the solution look as expected or does it look like there was a problem?

**Comment by Porkking** [comment]
The unit is weird to me. I set the output wind height as 1000m, while the result gives me an altitude which maximum is 7000m. Also, what is the unit of output wind?
