### ISSUE TITLE
small miscelaneous issues

### ISSUE THREAD

**Issue by santiagoMonedero** [firelab/windninja#420]
Some small issues that I am not sure are worth opening an independent issue. Using CLI v3.7.2  I noticed:

1) If the `output_path` keyword is not set, then the `write_wx_station_csv` is not generated. The reason is that `pointInitialization::writeStationOutFile` does not check if the `basePath `is empty to replace it with the path of the input folder like `write_wx_station_kml` does
2) The `wxStation::GetHeaderVersion()` in the point initialization gives an error if the *csv file does not contain comma after the `Station_File_List` keyword. The **missoula_valley_stations_4.csv** example file is missing that comma and gives an error.  
3) The **cli_pointInitialization_diurnal.cfg** example file does not work because it uses the old `end_* `nomenclature instead of the new `stop_*` nomenclature to define the end date.
4) The `fetch_station` keyword gives a conflict with the `wx_station_filename` even if it is set to **false**. To work, it has to be completely removed from the cfg.
5) line 1473 in **cli.cpp** I think the `i` in `CPLDebug("STATION_FETCH", "Writing wxStation csv for step #%d", i);` should be an `i_`  (was giving me a compilation error)
Hope it helps

**Comment by nwagenbrenner** [comment]
Thanks @santiagoMonedero. Number 3 has been fixed in a recent commit, but we need to address the other points here as well.

**Comment by nwagenbrenner** [comment]
Fixed with the merge of the `misc_issues` branch.
