### ISSUE TITLE
Point Initialization end_year exception

### ISSUE THREAD

**Issue by alcliberal** [firelab/windninja#423]
Iam trying to run a Point Initialization and I received this error:

`Exception caught: unknown option end_year`

But I wrote the `end_year` on the .cfg

My .cfg :

num_threads              = 1
elevation_file           = C:\Users\Alexandre Liberal\Documents\TG\DadosAdaiana\tirao.tif
initialization_method    = pointInitialization
time_zone		 = America/Recife
wx_station_filename	 = C:\Users\Alexandre Liberal\Documents\TG\DadosAdaiana\WXSTATION-1996-01-01-2016-12-31-tirao
start_year		 = 1997
start_month	         = 01
start_day		 = 01
start_hour		 = 00
start_minute		 = 00
end_year		 = 2016
end_month		 = 12
end_day			 = 31
end_hour		 = 23
end_minute		 = 00
write_wx_station_kml	 = true
output_wind_height       = 80.0
units_output_wind_height = m
vegetation               = trees
diurnal_winds		 = true
mesh_resolution          = 250.0
units_mesh_resolution    = m
write_shapefile_output   = true
write_pdf_output	 = true

I used 5 weather stations data that I haved and after change to the write format I put then the folder `WXSTATION-1996-01-01-2016-12-31-tirao`

Files in `wx_station_filename` : 

tirao_stations_5.csv
MCP137-UTC-1997-01-01_0000-2016-12-30_2300-0.csv
MCP244-UTC-1997-01-01_0000-2016-12-30_2300-1.csv
MCP245-UTC-1997-01-01_0000-2016-12-30_2300-2.csv
MCP252-UTC-1997-01-01_0000-2016-12-30_2300-3.csv
MCP273-UTC-1997-01-01_0000-2016-12-30_2300-4.csv

File `tirao_stations_5.csv` : 

Station_File_List,
MCP137-UTC-1997-01-01_0000-2016-12-30_2300-0.csv
MCP244-UTC-1997-01-01_0000-2016-12-30_2300-1.csv
MCP245-UTC-1997-01-01_0000-2016-12-30_2300-2.csv
MCP252-UTC-1997-01-01_0000-2016-12-30_2300-3.csv
MCP273-UTC-1997-01-01_0000-2016-12-30_2300-4.csv

First 5 lines of `MCP137-UTC-1997-01-01_0000-2016-12-30_2300-0.csv` : 

Station_Name,"Coord_Sys(PROJCS,GEOGCS)","Datum(WGS84,NAD83,NAD27)",Lat/YCoord,Lon/XCoord,Height,"Height_Units(meters,feet)",Speed,"Speed_Units(mph,kph,mps,kts)",Direction(degrees),Temperature,"Temperature_Units(F,C)",Cloud_Cover(%),Radius_of_Influence,"Radius_of_Influence_Units(miles,feet,meters,km)",date_time
MCP137,GEOGCS,WGS84,-10.457472222222222,-43.42391666666666,80,meters,5.161,mps,118.2,,,,-1,km,1997-01-01T00:00:00Z
MCP137,GEOGCS,WGS84,-10.457472222222222,-43.42391666666666,80,meters,4.628,mps,117.6,,,,-1,km,1997-01-01T01:00:00Z
MCP137,GEOGCS,WGS84,-10.457472222222222,-43.42391666666666,80,meters,5.339,mps,119.1,,,,-1,km,1997-01-01T02:00:00Z
MCP137,GEOGCS,WGS84,-10.457472222222222,-43.42391666666666,80,meters,3.884,mps,129.6,,,,-1,km,1997-01-01T03:00:00Z

**Comment by nwagenbrenner** [comment]
@alcliberal I think the argument should be `stop_year` instead of `end_year`. You can double check the correct variable name to pass into WindNinja by running `WindNinja_cli --help`. This is will display all of the CLI options.

**Comment by alcliberal** [comment]
Thank you! Sorry for my silly question.

**Comment by nwagenbrenner** [comment]
No problem, glad it's working for you now.

**Comment by alcliberal** [comment]
Looking the example files, I found why I used "end_year". The example file `cli_pointInitialization_diurnal.cfg` have end_year, end_month, end_day, end_hour and end_minute

**Comment by nwagenbrenner** [comment]
Thanks for catching that, we'll get that example cfg file updated.
