### ISSUE TITLE
movedynamicmesh.exe Windows block

### ISSUE THREAD

**Issue by tsopperman** [firelab/windninja#424]
Wind Ninja 3.7.2
Used the surface input>download file>LCP type.
Got the attached pop-up message.
Had to close it to continue.
Run seemed to process regardless, but I don't know if it mattered or not.
If I had walked away to let this process, not sure it 
![Capture](https://user-images.githubusercontent.com/88205238/127687461-db66e2ec-b875-4ace-8f11-342c97628a4b.JPG)
would've finished without my interaction.

**Comment by nwagenbrenner** [comment]
Yes, this warning always comes up the first time with a new Windows installation. We have an explanation of this on our download page, but it's easy to miss. The warning can just be dismissed, but the simulation should complete normally even if the warning isn't dismissed until the end of the simulation. Thanks for reporting this and please let us know if you encounter other issues.
