### ISSUE TITLE
Problem with fuel depth units

### ISSUE THREAD

**Issue by santiagoMonedero** [firelab/windninja#426]
Hi, I think there may be a problem with the fuel depth units used to compute the terrain roughness. While fuel depth units are  hard-coded in meters `(readInputFile.cpp L256)`, the actual vales are obtained in the following method in feet.
https://github.com/firelab/windninja/blob/3c9ffbfa744ff7f2a3fc11a4c52928ea83af3a67/src/ninja/ninja.cpp#L4777
This leads, for example, to a wrong calculation of the friction velocity using Albinis logarithmic wind profile, since the height above the ground is in meters, but the roughness length and the zero-plane displacement are in feet.
https://github.com/firelab/windninja/blob/3c9ffbfa744ff7f2a3fc11a4c52928ea83af3a67/src/ninja/domainAverageInitialization.cpp#L169

**Comment by nwagenbrenner** [comment]
@santiagoMonedero Thanks for filing this issue. I'll try to take a look in the next day or so.

**Comment by nwagenbrenner** [comment]
@santiagoMonedero Good catch. `getFuelBedDepth` is incorrectly returning the depth in feet. I'm adding a commit to fix this in the master branch.

**Comment by nwagenbrenner** [comment]
Fixed in bccc0ce.
