### ISSUE TITLE
WindNinja simulations unable to smooth discontinuities associated with initial conditions

### ISSUE THREAD

**Issue by EricKeenan** [firelab/windninja#427]
First of all, thank you for the excellent project. It's been a pleasure to use! 

I'm using WindNinja to downscale global reanalysis wind speed and direction (roughly 30 km horizontal resolution) to a higher resolution 1 km grid. However, it seems when using `initialization_method = griddedInitialization`, the model is unable to smoothen discontinuities associated with the initial conditions (~30 km intervals). Have you seen anything like this before? Any idea how I might achieve a more "continuous" solution? 

Here are my time averaged WindNinja downscaling results for 1 month. You see the vertical and horizontal stripes? Note that the superimposed non-linear ripples are topographically driven (this is great! need to preserve these...)

<img width="400" alt="1month_NN" src="https://user-images.githubusercontent.com/44210245/137171132-6da31e3e-9fec-4cad-981a-2923c871f56e.png">

As an example, this is what the input wind speed looks like (only 1 timestamp, i.e. no averaging as in the previous plot). I use a nearest neighbor approach to project the global reanalysis onto a regular 30 km grid. 

<img width="380" alt="Input" src="https://user-images.githubusercontent.com/44210245/137171424-1fdd4e7b-958f-493f-8321-b2ebc8f098bd.png">

My config file for reference
```ini
# Computing details
num_threads                = 1

# Input
elevation_file             = input/PIG.tif
input_speed_units          = mps
input_wind_height          = 10.0
units_input_wind_height    = m
input_speed_grid           = input/
input_dir_grid             = input/

# Ouput
output_path                = output/
output_wind_height         = 10.0
units_output_wind_height   = m
output_speed_units         = mps
ascii_out_resolution       = 1000.0
units_ascii_out_resolution = m
write_ascii_output         = true
write_goog_output          = false
write_shapefile_output     = false
write_farsite_atm          = false

# Settings
initialization_method      = griddedInitialization
vegetation                 = grass
mesh_choice              = fine
```

**Comment by nwagenbrenner** [comment]
@EricKeenan can you send me the input speed and direction grids and your DEM so I can reproduce this example? I'm not sure what might be going on, but I'll take a look if you can send me those inputs.

**Comment by EricKeenan** [comment]
@nwagenbrenner Thanks for looking into this. I will report back in more detail ASAP.
