### ISSUE TITLE
Find an ip <-> location api or database

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#429]
`ipstack` is limited to 100 queries/month.  An file-based db would be best, API if not.  Maybe try:

https://api.iplocation.net/

**Comment by nwagenbrenner** [comment]
@RuiZhang-kwf8 you are working on this as a part of #481 so adding you to this one. Can you add some notes to this issue with details about the service that you have implemented?

**Comment by nwagenbrenner** [comment]
Completed.
