### ISSUE TITLE
Error during blockMesh()

### ISSUE THREAD

**Issue by jzanetti** [firelab/windninja#435]
Dear WindNinja development team,

We are exploring the use of mass-momentum solver in WindNinja, however we get the error at the step of `blockMesh`, may I ask if you could help us to understand this error a bit more, or if you could repeat this error on your side (I've tried to look at the codes for the cause of the error but still haven't got any clue so far ...). Thank you very much.

The details of the problem is elaborated below:

- **System**: 
    The docker image built by `https://github.com/firelab/windninja/blob/master/Dockerfile`, and the program is run in Linux
- **Configuration**: 
    The configuration file used is `/opt/src/windninja/data/cli_momentumSolver_diurnal.cfg`
- **Run method**:
    The program is run by ` ./WindNinja_cli cli_momentumSolver_diurnal.cfg`
- **Error**:
    The error is:
    ```
    Run 0: Reading elevation file...
    Run 0: Simulation time is 2011-Sep-23 13:30:00 MDT
    Run 0: Run number 0 started with 1 threads.
    Run 0: Writing OpenFOAM files...
    Run 0: Converting DEM to STL format...
    Run 0: Transforming surface points to output wind height...
    Run 0: Generating mesh...
    Run 0: Running blockMesh...
    Exception caught: Error during blockMesh().
   Exception caught: Error during blockMesh().
    ````
Thanks for your help

Regards, 

Sijin Zhang

New Zealand Meteorological Service

**Comment by jzanetti** [comment]
Hi @nwagenbrenner, thanks for your reply (sorry for the slow response from my side, I did not get the github notification for some reason).

Following your leads, I've made `blockMesh` working on our machine, however it leads to another an error with even less information, can I ask if you could help to have a look when you have time ?

### How I got through the `blockMesh` error
- I've noticed that there are a few libs missing for `blockMesh`, so I manually linked those libs as:

> `export LD_LIBRARY_PATH= /opt/openfoam4/platforms/linux64GccDPInt32Opt/lib:/opt/openfoam4/platforms/linux64GccDPInt32Opt/lib/openmpi-system:$LD_LIBRARY_PATH`

- Then the program says it can't find `controlDict`. After gone through the codes, I've defined the environmental variable as:

> `export WM_PROJECT_DIR=~/OpenFOAM/run`

### New Segmentation fault error

After the above steps finally I can get through the `blockMesh` step, however immediately it leads to another error as:
```
NINJAFOAM: ymin = 5187312.837353
NINJAFOAM: zmin = 2649.128482
NINJAFOAM: xmax = 736790.744099
NINJAFOAM: ymax = 5217438.290369
NINJAFOAM: zmax = 6166.569644
Run 0: Converting DEM to STL format...
Run 0: Transforming surface points to output wind height...
NINJAFOAM: firstCellHeight = 336.597240
NINJAFOAM: displacementVelocity = 168.298620
Run 0: Generating mesh...
Run 0: Running blockMesh...
NINJAFOAM: simpleFoamEndTime = 2050
NINJAFOAM: simpleFoamEndTime = 2050
Segmentation fault (core dumped)
```
I am running on a machine with 24 Gb memory, and I am watching the memory usage closely, to me seems it is not a memory issue (unless ninjafoam requires more memory than this). I've applied `ulimit -s unlimited` however it does not help.

This error does not give much information, appreciate if you could help to point me to the possible reasons ? Thank you again !

Note, I am using the docker built by the provided [Dockerfile](https://github.com/firelab/windninja/blob/master/Dockerfile), and the configuration is the sample [cli_momentumSolver_diurnal.cfg](https://github.com/firelab/windninja/blob/master/data/cli_momentumSolver_diurnal.cfg)

Regards, Sijin

**Comment by jzanetti** [comment]
Update: by running `moveDynamicMesh` again, I got the error of:
```
--> FOAM FATAL IO ERROR:
cannot find file

file: /opt/src/windninja/data/system/controlDict at line 0.

    From function regIOobject::readStream()
    in file db/regIOobject/regIOobjectRead.C at line 72.

FOAM exiting
```

**Comment by jzanetti** [comment]
**Update**

I've found the issue:

The reason for the failure is that I did not install `openfoam2.2` (as clearly stated in the tutorial) separately. In the `Dockerfile`,  `openfoam4` is installed and I assumed that it is all the `openfoam` software we need, apparently I was wrong.

By manually installed `openfoam2.2`, I am not able to run the momentumSolver without any problem !

Thanks for your help on this, this ticket is closed with this comment

Sijin

**Comment by nwagenbrenner** [comment]
@jzanetti Glad you got the issue sorted out and it's working for you now. Thanks for following up here and closing the ticket.
