### ISSUE TITLE
License can not be both Public Domain and Open Source.

### ISSUE THREAD

**Issue by TedTschopp** [firelab/windninja#437]
License for this repo states that the code is public domain.  The license then goes on to contradict this and say the code is copyrighted.  This is a contradiction in legal terms, and thus a bug.  

As it stands right now TITLE 17 SECTION 105 OF THE UNITED STATES CODE prohibits a copyright being applied to government code.  Thus you can not make a stipulation on how the code is used or reused.   I recommend that the team work with a lawyer to get this aligned either to an Open Source License or to the Public Domain declaration and to reduce the legal risk this places the authoring term under as there appears to be a conflict with federal laws.

**Comment by nwagenbrenner** [comment]
The license was reviewed and approved by the Office of the General Council. It was determined that a blend of public domain language and open source language is as good as we can do.
