### ISSUE TITLE
Upcoming NOMADS server changes could include directory changes for our models

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#440]
From NOMADS:

Users,

NCEP is currently working on the transition of our model suite to a set of new supercomputers. This transition is currently slated to go live at the end of June, although that date may change due to Critical Weather Day or other factors.

This transition will mean some changes to directory structure for models on both NOMADS and FTPPRD which may impact some users. We are still working to compile the full list of changes and will advertise everything in an SCN ahead of time.

As well, we will be performing two 24hr tests where we do full dissemination off of the new systems before the official go-live date. These tests will take place approximately at the end of May and mid-June. Users will get notice through this mailing list before each test and the dates will be advertised in the SCN as well.

We are excited to move to this new infrastructure and hope to make this as transparent for you as possible. We will be happy to help with any questions you may have about the transition once the SCN is available to the public.

**Comment by greynathan** [comment]
Everything works, no code required
