### ISSUE TITLE
Exception caught: User Provided start and stop times are both outside datasets time span!

### ISSUE THREAD

**Issue by ajaugust** [firelab/windninja#447]
I am attempting to do a pointInitialization run on a WN downloaded DEM with WN downloaded station data. I have provided start and stop times that are a day apart.  I get the following error message:
```
Exception caught: User Provided start and stop times are both outside datasets time span!
```
What causes this exception?

**Comment by ajaugust** [comment]
Here is the config:
```
fetch_type               = bbox
match_points             = true
write_wx_station_csv     = false
station_buffer           = 10.0
station_buffer_units     = km
fetch_station            = true
number_time_steps        = 1
num_threads              = 8
elevation_source         = lcp
initialization_method    = pointInitialization
number_of_iterations     = 2000
mesh_resolution          = 120
units_mesh_resolution    = m
time_zone                = America/Los_Angeles
uni_air_temp             = 80.0
air_temp_units           = F
output_wind_height       = 20.0
units_output_wind_height = ft
diurnal_winds            = true
write_goog_output        = true
write_shapefile_output   = false
write_ascii_output       = true
write_farsite_atm        = true
momentum_flag            = false
```

And here is the run command:
```
\WindNinja_cli \
--config config.cfg \
--start_year 2003 \
--start_month 8 \
--start_day 18 \
--start_hour 16 \
--start_minute 0 \
--stop_year 2003 \
--stop_month 8 \
--stop_day 20 \
--stop_hour 16 \
--stop_minute 0 \
--output_path .\output \
--elevation_file dem.lcp
```

Thanks!

**Comment by latwood** [comment]
Seems kind of strange to set number_time_steps equal to 1 while using
different start and stop times. Everything else looks good, and I was able
to get it to run fine when using the missoula_valley.tif file from the
WindNinja data folder. Looks like it only output a single time for the
station .csv files, times close to the chosen simulation time which was an
average between the start and stop times, so 2003-Aug-19 09:00:00 PDT which
is 2003-Aug-19 16:00:00 GMT (4:00 pm).

I then downloaded my own dem.tif from a very small area near LA, and was
able to replicate the error. It looks like it is still downloading a single
time for the station .csv files, but all the times are less than the chosen
simulation time of 2003-Aug-19 16:00:00 GMT. Looks like the
missoula_valley.tif station .csv files had a single data point at exactly
2003-Aug-19 16:00:00 GMT, all the rest of the data were for times less than
the chosen simulation time of 2003-Aug-19 16:00:00 GMT.

I then ran the dem.tif file again, with everything the same, but this time
using number_time_steps equal to 2. This time I got station .csv files with
what I would consider to be a more full list of time data, and the
simulation chose simulation times of 2003-Aug-18 09:00:00 PDT and
2003-Aug-20 09:00:00 PDT. Repeating this one last time with
number_time_steps equal to 3, and I got the more full list of time data and
the simulation chose simulation times of 2003-Aug-18 09:00:00 PDT,
2003-Aug-19 09:00:00 PDT, and 2003-Aug-20 09:00:00 PDT and this time it
worked for the 2003-Aug-19 09:00:00 PDT time. So it seems like it somehow
didn't download enough data when running for a single time. Trying start
and stop time of the same value of 2003-Aug-19 16:00:00 GMT and
number_time_steps equal to 1, I got the same error and the same station
.csv files with time data all less than 2003-Aug-19 16:00:00 GMT.
Replicating all this with missoula_valley.tif I had no problems.


So it does seem like there is some kind of undefined behavior for single
timestep simulations, at least for this particular case. I have yet to
verify if it was just luck of the draw and this specific case just didn't
have much data for that one specific time, or if some improvements need
made to the solver. For now, it seems like downloading data for multiple
times then using that single set of station .csv files for multiple
simulations of different start and stop times and number_time_steps within
the data of the single set of station .csv files might be a good
workaround. Try checking out the various cli_pointInitialization_<different
names>.cfg files in the WindNinja data folder, here:
https://github.com/firelab/windninja/tree/master/data

**Comment by latwood** [comment]
Let me phrase that better. Try downloading a single set of station .csv
files for the full time between the start and stop times once, then use
that file as an input while picking various start and stop times and the
corresponding number of timesteps you want for each of your desired
simulations. You've already got what you need to get the station .csv
files, just need to run that again with number_time_steps equal to
something other than 1. Looks like cli_pointInitialization_timeseries.cfg
is what you want to run time series on an already downloaded set of station
.csv files, here:
https://github.com/firelab/windninja/blob/master/data/cli_pointInitialization_timeseries.cfg
.

Let us know if this works, or if you need something different, it isn't
quite clear to me with your example whether you are trying to run a single
time or if you are trying to run multiple timesteps.

Thanks :)

Loren Atwood

**Comment by ajaugust** [comment]
Hi @latwood, Thanks for your response. I am indeed trying to run one simulation at a specific date for this dem. I provided a date range around my date because I wasn't sure if a station measurement would exist on that date, but if there's a station measurement within a couple days, that works too.  How would you advise doing a single timestep run in this case?

**Comment by nwagenbrenner** [comment]
@ajaugust Your start and stop times will need to be spanned by the station file dates/times. Once you've downloaded/uploaded a station file, just set your start/stop times to be within the range of your dates/times in your station file. If there is only one time step in your file, then you can either set both start and stop times to that time and the number of time steps to one or use the single time step station format. If you try this in the GUI, the GUI will autodetect valid start/stop times for you. You could try this as a test to see figure out how to set up your CLI run.

**Comment by ajaugust** [comment]
Thanks. I set number_time_steps = 2 (instead of 1) and now the runs are running. 

I originally wanted to download weather data for one point in time and run one simulation, but I realize that time may not be available, so I buffered with a start/stop time of +/- 1 day, set number_time_steps = 2 and ignored one of the simulation outputs.
