### ISSUE TITLE
Certificate Error downloading lcp - cli on linux

### ISSUE THREAD

**Issue by tcarternws** [firelab/windninja#448]
Hi,
I get the error below running WindNinja_cli version 3.7.2, gdal version 2.2.2
This particular run was for LCP elevation file.

Downloading elevation file...
ERROR 1: Peer's Certificate issuer is not recognized.
Warning 1: Failed to get job status
Failed to download elevation data

The build_deps.sh is configured for a very old version of gdal. Is there any way to bypass certificate checking or otherwise get by the certificate issue with a gdal update or similar action?

Thanks,
Todd
RH 7

**Comment by nwagenbrenner** [comment]
Hi Todd, I just pushed 51d4e6f to the master branch that bypasses the certificate checking for now. This should fix your issue. Please re-open this issue if there are still problems.
