### ISSUE TITLE
LANDFIRE services are changing

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#451]
The current requestValidationService and DownloadService we use to fetch the LCP data are being retired. Scheduled retirement is July 1. We need to switch to the new [Landfire Product Service]( https://lfps.usgs.gov/arcgis/rest/services/LandfireProductService/GPServer). A example Python script for using this service is attached here.

[submit_check_retrieve.txt](https://github.com/firelab/windninja/files/8632326/submit_check_retrieve.txt)

**Comment by jforthofer** [comment]
WindNinja code that currently handles this is:
https://github.com/firelab/windninja/blob/master/src/ninja/landfireclient.cpp

**Comment by nwagenbrenner** [comment]
We added code to handle the new GTiff format for landscape files (in addition to the LCP format), but we need to double check that non-landscape GTiff files (SRTM, GMTED, etc. DEM files) are still read correctly. We should check for the number of bands in the GTiff. If there are more than one, it's a landscape file, otherwise it's a DEM. See https://github.com/firelab/windninja/blob/master/src/ninja/readInputFile.cpp#L401.

**Comment by nwagenbrenner** [comment]
This is fixed in the lcp-service-upgrade branch. We just need to edit tutorials, example files, etc. to replace *.lcp with *.tif. All landscape files downloaded by WindNinja will now be multi-band GeoTIFF files (not .lcp files). Reading the older .lcp format is still supported though. Then we'll merge this into the master and prepare a release.

**Comment by nwagenbrenner** [comment]
Fixed in e2d0e01 through 1a3dcab.
