### ISSUE TITLE
Compile Error: Overload a function with 'C' linkage

### ISSUE THREAD

**Issue by santiagoMonedero** [firelab/windninja#453]
Hi, I am trying to compile  Windninja for cli (no openfoam, no Qt, no nomads) and I am getting the following compiling errors in both Linux and Windows:

``
Scanning dependencies of target ninja
[  1%] Building CXX object src/ninja/CMakeFiles/ninja.dir/windninja.cpp.o
/home/computeadmin/ninjafirelab/windninja/src/ninja/windninja.cpp: In function ‘NinjaH* NinjaCreateArmy(unsigned int, ch                          ar**)’:
/home/computeadmin/ninjafirelab/windninja/src/ninja/windninja.cpp:91:29: error: conflicting declaration of C function ‘N                          injaH* NinjaCreateArmy(unsigned int, char**)’
 WINDNINJADLL_EXPORT NinjaH* NinjaCreateArmy
                             ^~~~~~~~~~~~~~~
In file included from /home/computeadmin/ninjafirelab/windninja/src/ninja/windninja.cpp:30:0:
/home/computeadmin/ninjafirelab/windninja/src/ninja/windninja.h:82:33: note: previous declaration ‘NinjaH* NinjaCreateAr                          my(unsigned int, int, char**)’
     WINDNINJADLL_EXPORT NinjaH* NinjaCreateArmy
                                 ^~~~~~~~~~~~~~~
src/ninja/CMakeFiles/ninja.dir/build.make:1838: recipe for target 'src/ninja/CMakeFiles/ninja.dir/windninja.cpp.o' faile                          d
make[2]: *** [src/ninja/CMakeFiles/ninja.dir/windninja.cpp.o] Error 1
CMakeFiles/Makefile2:1034: recipe for target 'src/ninja/CMakeFiles/ninja.dir/all' failed
make[1]: *** [src/ninja/CMakeFiles/ninja.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2``

As a work around I have removed the following overloaded constructors that was only used for the FOAM case in previous windninja versions:

https://github.com/firelab/windninja/blob/e8483a5b790c5afec9c1928c00749058eba9d3de/src/ninja/windninja.h#L82

This fixes the issue (windninja seems to work fine) but I guess it not the best approach.
Any suggestion?  Thanks

**Comment by nwagenbrenner** [comment]
@santiagoMonedero I think 8c40972 solves this compilation issue. Please let me know if it doesn't.

**Comment by santiagoMonedero** [comment]
Yes, that is the same changed I made so it should work. Thanks @nwagenbrenner.
