### ISSUE TITLE
Upgrade OpenFOAM version -- Use old precompiled OpenFOAM 2.2.0 for Windows builds, new OpenFOAM 8 for Linux builds

### ISSUE THREAD

**Issue by latwood** [firelab/windninja#458]
Natalie has been working on getting WindNinja to compile on newer versions of Ubuntu. She was able to get WindNinja to compile fine, but ran into problems getting OpenFOAM 2.2.0 to work. It was determined that it would be easier to just switch to a newer version of OpenFOAM for Linux builds, but still use the old Windows precompiled OpenFOAM 2.2.0 libraries for Windows builds while they are still working for Windows builds.

I've already been working with OpenFOAM 8 for the last year or so for another project. I did a conversion of the WindNinja BCs, studying the changes in the inheritance structure of the libraries to make sure that they would still produce the same behavior, that they were the same or similar set of equations. I confirmed that the BCs should be behaving as they used to in OpenFOAM 2.2.0, but I seemed to run into trouble with the numerics (fvSchemes, fvSolution entries), my simulations would blow up until I used a modified version of the OpenFOAM 8 windAroundBuildings tutorial numerics. But my problem with replicating the original WindNinja OpenFOAM 2.2.0 numerics may have been because the simulations I was running were at a much smaller scale than typical WindNinja simulations. My simulations were for a much smaller domain size, much higher resolution, than typical WindNinja simulations (more cells at higher resolution in the layers near the ground than WindNinja).

Then, in the last two months, I tested slope flow for my project. I ran the WindNinja momentum solver on an lcp file of a very small area swept out on the map (329.184 m x 329.184 m = 1080 ft x 1080 ft), then converted the case to run in OpenFOAM 8. So I didn't run moveDynamicMesh, topoSet, or refineMesh in OpenFOAM 8, though later I added a building using snappyHexMesh which is similar, nor have I run the WindNinja controlDict sampledSurfaceDict function stuff in OpenFOAM 8, but for everything else it was just small changes in entries to files to get the WindNinja OpenFOAM 2.2.0 cases to run in OpenFOAM 8.

So I'm going to add what I have, then go from there until we can run WindNinja running on OpenFOAM 8 for Linux builds, but still running off of OpenFOAM 2.2.0 for Windows builds.

Note that I did my project work using Ubuntu 16.04, so I already know that OpenFOAM 8 works on Ubuntu 16.04, I'll be doing this upgrade on Ubuntu 20.04.

**Comment by latwood** [comment]
Just tested out simpleFoam with both my porous media "oldBCs" and the WindNinjaBCs, the fvSchemes and fvSolution files for the two sets of numerics that I've used in the past. Looks like it was able to run both of them fine, the result looked similar for both. It IS possible that this could be an artifact of applyInit hiding that the values aren't updating because they are already starting out at close to the original values, but I think we should test that at the end after we get WindNinja to fully run with OpenFOAM 8.

This leaves figuring out what is the equivalent of "sample", then WindNinja should run with all the changes that I've made so far. I suspect that the reason it is dying at writeFoamFiles() right now is because I tried adding "uniform" between "z0" and "$value$" and it didn't like that, if that's the case then I'll have to do it directly in the code with an if define win 32. Surprisingly, I haven't needed to do such if define win 32 yet, just had to update the /data/ninjafoam/8/ files.

Then after that, there are a few system files that seem to just hang around, we need to decide whether we want to track down what they should be in OpenFOAM 8 via looking at the /opt/openfoam8/tutorials/. I do have a few examples of snappyHexMesh in my porous media simulations, but they seem to be for a different type of application.

**Comment by nwagenbrenner** [comment]
Tested on Ubuntu 20.04 and windows. Everything looks good and this work has been merged into the master branch.

**Comment by latwood** [comment]
This commit was related to this upgrade, apparently I had forgotten to update the case file reuse when doing the foam 8 upgrade, but especially so when I added the probe sampling for massMeshVtk stuff.

42fff7dc05c83e53303de0c147f6979648ed341e
