### ISSUE TITLE
Memory outputs do not cover input DEM

### ISSUE THREAD

**Issue by stubrittain** [firelab/windninja#474]
Memory grid outputs can be smaller than the DEM and will not cover a landscape

**Comment by stubrittain** [comment]
Never mind, I will  deal with it.

**Comment by nwagenbrenner** [comment]
This is a FlamMap/FARSITE-specific issue, but we could call `BufferToOverlapGrid` in `get_outputSpeedGrid` and `get_outputDirectionGrid` if `outputBuferClipping` > 0.0 like we do in writeOutputFiles for the GUI and CLI for FlamMap.

https://github.com/firelab/windninja/blob/master/src/ninja/ninja.cpp#L2841

https://github.com/firelab/windninja/blob/master/src/ninja/ninja.cpp#L4477

**Comment by stubrittain** [comment]
Yep, it is Farsite/FlamMap specific, so I will just use winds of zero when outside the grid. As far as I am concerned you can get rid of the buffering for the output grids as well once I make sure Farsite and FlamMap allow it.

**Comment by nwagenbrenner** [comment]
Okay, sounds good.

**Comment by jforthofer** [comment]
Stu, another thing you could consider is to do a "nearest neighbor" type filling for cells that don't have needed values.  So this would buffer out the wind grids where needed with the nearest neighbor's wind values.  At least then the fire behavior modeling users wouldn't see some weird boundary effect on fire behavior.  Something to consider if it's easy to do.  That is the method we use to buffer (and autofill DEMs that have no_data values).

**Comment by stubrittain** [comment]
That's alright, I will just go "pure" and consider anything without wind data as just that, nodata. So zero wind. Alternatively, if Chuck decides so we can just use whatever is in the weather stream, or do the interpolation, but I want to get away from "making up" data.

**Comment by jforthofer** [comment]
I hear you about "making up data".  On that note, would it be OK if WindNinja stopped doing this wind buffering thing?  It was only done for Farsite/FLAMMAP.  My preference would be that we just spew out the true wind simulation output, and anyone that needs to buffer or whatever in their model (fire behavior model, avalanche danger modeling, wind erosion on Mars, etc.) can do it themselves.

**Comment by stubrittain** [comment]
As for me yes, it would be OK to get rid of the buffering once I have validated Farsite and FlamMap deal with it. Right now it is just a check on inputs loading that is failing. But we should clear it with Chuck at least. We have options, but I prefer to treat nodata as nodata. This may effect several rows/columns of data if the wind ninja resolution is a lot larger than the landscape resolution, so we may decide to use zeroes, may decide to interpolate, or may find a way to exclude those rows/columns.

**Comment by jforthofer** [comment]
Sounds good Stu.

**Comment by cwmchugh** [comment]
Jason, before you rip out your buffering code i want to make sure that what Stu is implementing in FlamMap (NoData assignment)  works as intended first..

**Comment by jforthofer** [comment]
Sounds good Chuck, let us know...

**Comment by stubrittain** [comment]
Closing as FlamMap and Farsite can both deal with it now
