### ISSUE TITLE
Possible error in the CheckForGridOverlap method in GriddedInitialization

### ISSUE THREAD

**Issue by santiagoMonedero** [firelab/windninja#495]
Hi, using Gridded Initializtion in Windninja v3.9 I am getting the following error which is not present in v3.8:

`Exception caught: The input speed and direction grids do not completely overlap the DEM.`

I have not compiled to debug the method, but just looking at the code there seems to be something odd in:
https://github.com/firelab/windninja/blob/97690b701f7d546fdc35091fcf1fd65a9fc2977e/src/ninja/ascii_grid.cpp#L903

1) In this method `xDist` seems to be used and named as the horizontal distance of the layer, but it is in fact defined as the eastern coordinate: `xDist = get_xllCorner() + get_nCols()*get_cellSize();` so the following conditions is not correct
`A.get_xllCorner() > (get_xllCorner() + xDist)` 
since it would be equivalent to
`A.get_xllCorner() > 2*get_xllCorner() + get_nCols()*get_cellSize()`
Just to put an example, if the weather_x0=-20 weather_x1=3, dem_x0=1 and dem_x1=2 with the  dem obviously completely overlapped by the weather,  the method would return false since
`dem_x0 = 1 > 2*(-20)+23=-17`  is true

2) Also, the method does not check if the DEM eastern/northern points (xmax, ymax) are inside the weather domain. 

I did a pull request with a simple fix for these issues in case you want to use it.

**Comment by nwagenbrenner** [comment]
Fixed in [9b1a61d](https://github.com/firelab/windninja/commit/9b1a61d3433b0407542ea54baee86be165884f47).
