### ISSUE TITLE
Installing WindNinja on an AWS EC2 Ubuntu server

### ISSUE THREAD

**Issue by DanielSWx** [firelab/windninja#505]
Apologies for all the questions! I have a coworker who is working to install WindNinja on an AWS ECU Ubuntu server, but has run into troubles. 

He wanted to confirm that the documentation on GitHub is aligned with the most current codebase, and if there is any assistance/guidance that could be provided to ensure successful installation. 

Thank you!

**Comment by latwood** [comment]
I've used this guide regularly to build on Ubuntu 20.04 desktop, many times
from scratch with nothing else on the machine or VM or ubuntu:
https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Linux.
Usually I have to add in a command
sudo apt update
sudo apt upgrade
sudo apt install build-essential   <-- gcc compiler
sudo apt install git vim cmake-gui

the rest of the dependencies are handled with the run of
build_deps_ubuntu_2004.sh, you can look at the file to see what commands it
is running. The sudo apt install openfoam8 command handles many of the
extra OpenFOAM dependencies, we followed the guide here for that package:
https://openfoam.org/download/8-ubuntu/. Alternatively, for building
openfoam 8 from scratch, there is this guide:
https://openfoam.org/download/8-source/, note the extra page here for
getting dependencies for compiling from sources:
https://openfoam.org/download/source/. This is similar to the old process
we used back when we used OpenFOAM 8:
https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Linux/507d3f7686933be983dbca53a299d9057fe3c166,
but note that we haven't tested building from source for OpenFOAM 8 yet as
we haven't yet had the need.


Anyhow, I don't know the details of Ubuntu server vs desktop, but if it's a
true server where you truly don't have a GUI, I bet the qt building stuff
is causing problems, should just need to drop building the qt stuff and
just build everything else, unchecking the NINJA_QTGUI and checking NINJA_CLI
when running cmake.

If you are also not able to use sudo apt install commands (shared
dependencies on the server), it gets a heck of a lot more complicated fast,
you start to run into the territory of needing to track and and build a lot
of the dependencies and dependencies of dependencies from scratch, pointing
the various paths in cmake to the appropriate source locations, we won't be
able to help more if this is the case. I have two convoluted examples:
1) the building WindNinja on windows (this one is definitely not as easy to
follow as the linux one, stuff sometimes breaks as dependencies age, plus a
whole separate style system) wiki page gives an example of this style
building:
https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Windows-using-the-MSVC-compiler-and-gisinternals.com-dependencies
2) I've also built a much older version of WindNinja without OpenFOAM on a
CentOS server (hasn't been checked to see if it still works for a while)
checking to build it on a clean VM of ubuntu 16.04, the build script is
convoluted and not easy to follow but it worked at the time I was using it
(3 years ago). One of these days I think I need to make a simpler example
just to help new folks practice compiling from sources, but for now it is
what it is:
https://github.com/latwood/WRF-WindNinja-FarsiteScript/tree/master/include

Yeah hopefully you don't need to deal with compiling stuff from sources, we
can't help you much if that is the case.


This is probably more information than you wanted/needed, but hope it helps.

Loren

**Comment by nwagenbrenner** [comment]
Yes, those instructions are current. If they continue to have issues,
please report the specific errors and we will try to help.
