### ISSUE TITLE
LCP service is broken

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#515]

**Comment by nwagenbrenner** [comment]
The service is just really slow right now. Increasing LCP_MAX_DOWNLOAD_TRIES from 40 to 200 just worked for me.

**Comment by rdwadhwani0220** [comment]
Hey Natalie, I modified landfireclient.cpp and increased LCP_MAX_DOWNLOAD_TRIES to 200 but it is still not working for us and I am unable to fetch the LCP elevation files.

**Comment by rdwadhwani0220** [comment]
@nwagenbrenner Sure, update me when you receive any solution. However, I increased to 5000 also but it failed to work for our case.

**Comment by nwagenbrenner** [comment]
The response from LANDFIRE:

_In the last several months, LFPS has been going through many changes. We are working to bolster and enhance LFPS, this has required some large changes in the background. We are aware of the increased processing time and are actively investigating the issue. Thank you for providing the details about your job, we hope to have the increased processing time issue resolved in the near future and we apologize for the inconvenience._

Maybe a good time to work on #459.

**Comment by nwagenbrenner** [comment]
Closing this since the issue is out of our hands. All we can do is look to host our own service and that is captured in #459.
