### ISSUE TITLE
Incorrect time zone reported in the GUI with point initialization

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#516]
The GUI is incorrectly reporting the local time of the machine (at least it appears this is what is happening) for the start/stop times instead of the DEM local time. There is also an issue with how many time steps we auto-detect in the GUI. For example, these station files only have one timestep each (the same timestep), but the GUI defaults to two timesteps. For this case of a single, constant time present in the station files, we should default to a single time step. I think the current behavior is to detect the min/max times present in the files and then set the start time to the min and the end time to the max. I'm not sure how the number of time steps gets set.

Files to reproduce:

[KARDZHALI-EET-2018-01-01_2022-12-31_0000-6.csv](https://github.com/firelab/windninja/files/14793846/KARDZHALI-EET-2018-01-01_2022-12-31_0000-6.csv)
[CHIRPAN-EET-2018-01-01_2022-12-31_0000-4.csv](https://github.com/firelab/windninja/files/14793848/CHIRPAN-EET-2018-01-01_2022-12-31_0000-4.csv)
[ELHOVO-EET-2018-01-01_2022-12-31_0000-5.csv](https://github.com/firelab/windninja/files/14793849/ELHOVO-EET-2018-01-01_2022-12-31_0000-5.csv)
[Test_5.tif](https://ninjastorm.firelab.org/data/Test_5.tif)

**Comment by latwood** [comment]
We found these earlier, but these two lines of code, especially the second
one, seem very suspect.

https://github.com/firelab/windninja/blob/3.10/src/gui/pointInput.cpp#L439
https://github.com/firelab/windninja/blob/3.10/src/gui/pointInput.cpp#L587

**Comment by nwagenbrenner** [comment]
Fixed in the master branch.
