### ISSUE TITLE
GFS is down at NCAR

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#63]
Ryan Mercovich @ SI reported on 2015-04-21

**Comment by fspataro** [comment]
We were seeing issues with UCAR forecast download late last week testing mobile.

**Comment by ksshannon** [comment]
@fspataro Just GFS, or all UCAR?

**Comment by fspataro** [comment]
Mobile app only has UCAR-NAM-CONUS-12-KM so it's at least that one too... I haven't tried it this week, I started defaulting to the NOMAND version.

**Comment by ksshannon** [comment]
@fspataro Thanks.

**Comment by ksshannon** [comment]
Temporary fix in 463cdb236a4798ea263f6e3421348b6b2a3c86ef, will be fixed for #16.

**Comment by ksshannon** [comment]
thredds.csv has been updated on marblerye.org as well, @jforthofer please test, and then close.

**Comment by ksshannon** [comment]
Folding into #16
