### ISSUE TITLE
ninjafoam options are messed up in the gui

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#71]
Non-available options (diurnal wind, non-neutral stability, etc) are no longer disabled when the momentum solver is selected. And progress is messed up. Maybe related to 0c70d51? Things were working at some point before this.

**Comment by ksshannon** [comment]
I'll check it...

**Comment by nwagenbrenner** [comment]
False alarm. It looks like the problem was on my side. Something got messed up in my build directory I guess (although I don't see how/where). I rebuilt in a fresh directory and the gui options seem okay now. Strange.
