### ISSUE TITLE
Remove patched open foam from the source tree

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#72]
Our download usually is close to exceeding the limits(for zip files), a 32MB binary will push us over.  I have put the tar up at:

ftp://windninja.org

We should either fork openfoam official repo, patch it, or just start a new repo with the patched version, or just use the ftp.

Removing a file permanently from git:

http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository

**Comment by nwagenbrenner** [comment]
I put it there so you could get to it and so we all knew where it was, but I didn't pay attention to the size. I guess do whatever you think is best?

**Comment by ksshannon** [comment]
I will make a repo and keep it there.  I just wanted to document what I was doing, I don't want to screw up...

**Comment by ksshannon** [comment]
Removed.  Cloned to ksshannon/windninja in case something went bonkers, it appears to have worked.

**Comment by ksshannon** [comment]
Natalie, can you try a pull without having to merge?  The tar was re-added in a merge and re-committed.

**Comment by nwagenbrenner** [comment]
Sorry I made a mess out of that. I'll just re-clone.

**Comment by ksshannon** [comment]
No worries, I did it a couple of times.  I'd just try a straight pull first...
