### ISSUE TITLE
Cross Compile OpenFOAM

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#77]
2.2.x is forked at http://github.com/firelab/OpenFOAM-2.2.x with a branch with the patch applied.  There is also a build script placeholder in the 'patched' branch.  This ticket will keep track of progress.

**Comment by ksshannon** [comment]
Tracking scripts in scripts/ninjafoam.  Each script does a little bit of the build process on Ubuntu.

- [ ] all.sh
- [ ] apt.sh
- [ ] foam_get.sh
- [ ] foam.sh
- [ ] msmpi.sh
- [ ] ninjafoam.sh
- [ ] zip.sh
- [ ] zlib.sh

**Comment by ksshannon** [comment]
Do we need the third party stuff, I guess libscotch specifically?

**Comment by nwagenbrenner** [comment]
Yes, I'm pretty sure scotch is required for parallel processing. It's used during domain decomposition.

**Comment by nwagenbrenner** [comment]
Sorry, actually I think we don't need it. We're using "simple" decomposition, which doesn't require scotch.

**Comment by jforthofer** [comment]
In the future if we switch to snappyHexMesh, do we then need scotch for decomposition?  Seems like a possibility since the mesh is more complex, but I haven't looked into it...

**Comment by nwagenbrenner** [comment]
No, we were using simple decomposition for snappyHexMesh too. It looks like using scotch allows you to do more sophisticated things like specify a weighting between processors, minimize the number of processor boundaries, and more precisely control how the decomposition is done.

**Comment by jforthofer** [comment]
OK, I'm no expert on this stuff, but someday we might want to try some of this out as it could reduce simulation times.  Minimizing the processor boundaries should limit message passing and speed up simulations.  I think it probably also does some optimization of cell/node numberings???

**Comment by jforthofer** [comment]
But for now, I'm cool with forgetting about it to get a version out...

**Comment by ksshannon** [comment]
Whittled down the archive size by loading what we actually use.  For the record, some OpenFOAM apps appear to load libraries at runtime, e.g. dlload or whatever the mutant mingw cross compile uses.  The current setup assumes no scotch, as I can't compile it yet.  Pertinent change:

https://github.com/firelab/OpenFOAM-2.2.x/commit/9e17c48e760c47ce68ccd5a8d5918da0a94dc75e

On another note, I believe I'll have the environment variables set up, with some hacked in starter code.  I will need to get with Natalie if the timestep/directory issue persists, as I don't know where to start.

**Comment by ksshannon** [comment]
I'd like to have a quick meet up (google chat maybe), to discuss how to handle cmake/ninjafoam.  The installer is completely dependant on the firelab build machine organization, and I haven't replicated that here.  I *think* I can write up how to do it, and write the proper cmake for the firelab machine, but we should chat.

**Comment by jforthofer** [comment]
OK, I'm here pretty much all day if you are free...

**Comment by ksshannon** [comment]
I'm at a loss, I can't compile scotch for the life of me, so I am stuck.  I also can't replicate a build on my laptop with an error regarding a missing src/OSspecific/POSIX/lnInclude/regExp.H.  I have seen this before, but can't remember what I did to fix this.  The entire system is fragile and illogical, I can't guarantee anything.

**Comment by ksshannon** [comment]
- [ ] Post OpenFOAM-2.2.x DP
- [ ] CMake
- [ ] Test installer on win32 and fs-win32

**Comment by ksshannon** [comment]
- [ ] Add wiki page with instructions

**Comment by nwagenbrenner** [comment]
I can take this over if it's easier to finish this up with access to a Windows machine. Seems like most of the steps are done, it's just the installer stuff in cmake and setting some environment variables, right? Just let me know what you prefer.

**Comment by ksshannon** [comment]
My x compile setup is a little simpler, although I am not totally sure it will work.  It's worked on my vm so far.  Basically, I put all of the libs in platforms/linux64mingw-w64DPOpt/lib and all the executables in the platforms/linux64mingw-w64DPOpt/bin.  So mpiexec, applyInit, etc. are all in the bin folder and libscotch, msmpi, libNinja are all in the lib folder.  This simplifies the install, and works on my vm using 1 thread/job.  It is not working on the installer yet.  Working on it.

**Comment by nwagenbrenner** [comment]
Yep, I get it. And can replicate it. Just offering to help because I was under the impression that this was something that wasn't convenient for you to work on?

**Comment by ksshannon** [comment]
My bad, that wasn't a direct response.  Just documentation.  I am pretty far, installer builds, appears to put stuff in the right place, but fails on run.  We can chat tomorrow on where to go next.  Apologies, I didn't see your comment until it was too late.

**Comment by nwagenbrenner** [comment]
Seems like we're done here. If there are other things we need to do, let's open specific tickets. We should probably add a wiki page describing this process.
