### ISSUE TITLE
Looks great! can I use a CLI?

### ISSUE THREAD

**Issue by liebrand** [firelab/windninja#85]
Hi there,

Windninja looks amazing! I've been looking for something that could produce local wind models for use in sailing. In particular to see how wind reacts around islands / inside the bay.

I noticed there is a linux build instruction; but what I'm really after is a command line interface? I'd love to be able to batch process GRIB or NC files, and produce shape or kmz output files for specific regions (eg SF Bay area).

Is such a thing possible?

**Comment by ksshannon** [comment]
liebrand,
See the docs for the CLI here:
https://github.com/firelab/windninja/blob/master/doc/CLI_instructions.pdf

The application can download various weather forecasts, see various docs for that here:
https://github.com/firelab/windninja/blob/master/doc/tutorials/WindNinja_tutorial4.pdf
https://github.com/firelab/windninja/blob/master/doc/nomads.md

**Comment by liebrand** [comment]
Thanks, I've been playing with just that; but kinda put it on the backburner as I was trying to get this working on MacOS.  I might give it a go in the next couple days again, or wait for the server component that's up and coming up

**Comment by ksshannon** [comment]
Ongoing email conversation, moving off issue tracker.
