### ISSUE TITLE
Use automated RAWS grabbing to do point initialization runs

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#94]
It would be nice if WindNinja had some ability to do point initialization runs by automatically downloading RAWS data.  There is a web service to access the RAWS data like this:

https://fam.nwcg.gov/wims/xsql/obs.xsql?stn=242902&sig=&type=R&start=9-Jul-13&end=9-Jul-13&time=23&sort=&ndays=&user=

Some info here might be useful:

http://fam.nwcg.gov/fam-web/WIMS_Technote_2015-03-WXML.pdf

**Comment by nwagenbrenner** [comment]
I think we should use probably use the mesowest/synopticlabs service. It includes additional stations such as ASOS and allows us to define bounding boxes, etc. to grab data from.

http://synopticlabs.org/api/

**Comment by nwagenbrenner** [comment]
Should we add a time variable to the wxStation class? We build a timeList vector whose length equals the number of ninjas to be run

https://github.com/firelab/windninja/blob/station-fetch/src/ninja/cli.cpp#L968-1004

Currently wxStation holds info for just one station. Should we add a time variable that is the raw time for the observation. Then we'll have to interpolate in time to get the number of time steps to match up with length of timeList. And we'll end up with a vector of wxStations for each timestep in timeList?

**Comment by nwagenbrenner** [comment]
To be done:

- [x] Write functions to fetch data from API
- [x] Add options in CLI
- [x] Write raw data to disk in new station format
- [x] Read new station format from disk
- [ ] Allow reading/simulation with previous file format (single timestep)
- [ ] Buffer time when requesting data to ensure we span start and stop times
- [ ] Temporal interpolation
- [ ] GUI changes
- [ ] Update tutorial and example station file
- [ ] Give credit to MesoWest/SynopticLabs

**Comment by nwagenbrenner** [comment]
Related issue #22.

**Comment by nwagenbrenner** [comment]
This is mostly done. I'll file separate tickets for the remaining steps.
